-- ============================================================
-- XAOU BOOK HELPER / DATA
-- ดึงจาก BookShop_Auto_xaou_Center_Size19.xml
-- ============================================================

Xaou_BookCategories = {
    "ทั้งหมด",
    "💊 ตำราโอสถ",
    "⚔ วิชาบ่มเพาะ",
    "⬆ ตำราเลื่อนวิชา",
    "☯ DLC บู๊ตึ้ง",
    "🌀 ทักษะ/เคล็ดวิชา",
    "✨ วิชาเวท",
    "✨ วิชาเวทพิเศษ",
    "🧿 ค่ายกล",
    "🗡 อาวุธวิเศษ",
    "💎 สมบัติลับ",
    "🛡 การป้องกัน",
    "🔥 หลอมสร้าง",
    "📜 ยันต์/อาคม",
    "🌿 วิชาหลิงจือ",
    "📖 หนังสือ/บันทึก",
    "📚 คัมภีร์อื่น ๆ",
    "📦 อื่น ๆ",
}

Xaou_BookList = {
    { text="📖 คัมภีร์โอสถไท่ซ่าง (ฉบับขาด)", id="DanFang_4", cat="💊 ตำราโอสถ", story="Xaou_BookProxy_001", sourceStory="BookShop_Dan_1", cache="ItemCache2" },
    { text="📖 ตำราชิงฟ้า", id="DanFang_8", cat="💊 ตำราโอสถ", story="Xaou_BookProxy_002", sourceStory="BookShop_Dan_1", cache="ItemCache3" },
    { text="📖 ตำรายาห้าจักรพรรดิ", id="DanFang_3", cat="💊 ตำราโอสถ", story="Xaou_BookProxy_003", sourceStory="BookShop_Dan_1", cache="ItemCache4" },
    { text="📖 ตำราโอสถ: ท่วงทำนองของสัตว์ป่า", id="YaoGuai_Bible", cat="💊 ตำราโอสถ", story="Xaou_BookProxy_004", sourceStory="BookShop_Dan_1", cache="ItemCache5" },
    { text="📖 ตำราโอสถ: ท่วงทำนองเหมื่นอารมณ์", id="Emotion_Bible", cat="💊 ตำราโอสถ", story="Xaou_BookProxy_005", sourceStory="BookShop_Dan_1", cache="ItemCache6" },
    { text="📖 ตำราโอสถ: แห่งชีวิต", id="DanFang_6", cat="💊 ตำราโอสถ", story="Xaou_BookProxy_006", sourceStory="BookShop_Dan_1", cache="ItemCache7" },
    { text="📖 สูตรญาณแห่งโชคชะตา", id="DanFang_5", cat="💊 ตำราโอสถ", story="Xaou_BookProxy_007", sourceStory="BookShop_Dan_1", cache="ItemCache8" },
    { text="📖 สูตรเซียนหลบทัณฑ์สวรรค์", id="DanFang_7", cat="💊 ตำราโอสถ", story="Xaou_BookProxy_008", sourceStory="BookShop_Dan_1", cache="ItemCache9" },
    { text="📖 สูตรเซียนโลกมนุษย์", id="DanFang_2", cat="💊 ตำราโอสถ", story="Xaou_BookProxy_009", sourceStory="BookShop_Dan_1", cache="ItemCache10" },
    { text="📖 เคล็ดตำราโอสถแท้", id="DanFang_1", cat="💊 ตำราโอสถ", story="Xaou_BookProxy_010", sourceStory="BookShop_Dan_1", cache="ItemCache11" },
    { text="📖 เคล็ดลับสู่แดนลี้ลับ", id="DanFang_9", cat="💊 ตำราโอสถ", story="Xaou_BookProxy_011", sourceStory="BookShop_Dan_1", cache="ItemCache12" },
    { text="📖 โอสถเทพเต๋าสวรรค์", id="God2_Dan", cat="💊 ตำราโอสถ", story="Xaou_BookProxy_012", sourceStory="BookShop_Dan_1", cache="ItemCache13" },
    { text="📖 คัมภีร์โอสถไท่ซ่าง", id="Gong6_Esoterica_6", cat="💊 ตำราโอสถ", story="Xaou_BookProxy_013", sourceStory="BookShop_Dan_1", cache="ItemCache14" },
    { text="📖 ตำราโอสถ: เก้าวิถีโอสถ", id="Gong6_Esoterica_8", cat="💊 ตำราโอสถ", story="Xaou_BookProxy_014", sourceStory="BookShop_Dan_1", cache="ItemCache15" },
    { text="📖 ตำราโอสถ: ร้อยวิถี", id="Gong6_Esoterica_5", cat="💊 ตำราโอสถ", story="Xaou_BookProxy_015", sourceStory="BookShop_Dan_1", cache="ItemCache16" },
    { text="📖 🔥 ตำราโอสถ: ต้นตำหรับโอสถ", id="Gong6_Esoterica_10", cat="💊 ตำราโอสถ", story="Xaou_BookProxy_016", sourceStory="BookShop_Dan_1", cache="ItemCache17" },
    { text="📖 🔥 ตำราโอสถ: หลอมกลั่นพริบตา", id="Gong6_Esoterica_4", cat="💊 ตำราโอสถ", story="Xaou_BookProxy_017", sourceStory="BookShop_Dan_1", cache="ItemCache18" },
    { text="📖 🔥 ตำราโอสถ: 速炼法", id="Gong6_Esoterica_9", cat="💊 ตำราโอสถ", story="Xaou_BookProxy_018", sourceStory="BookShop_Dan_1", cache="ItemCache19" },
    { text="📖 🔥 เทพหลอมวิชา", id="Gong6_Esoterica_11", cat="💊 ตำราโอสถ", story="Xaou_BookProxy_019", sourceStory="BookShop_Dan_1", cache="ItemCache20" },
    { text="📖 คัมภีร์วิชา: 万法归藏", id="Gong4_Esoterica_5", cat="⚔ วิชาบ่มเพาะ", story="Xaou_BookProxy_020", sourceStory="BookShop_Gong_1", cache="ItemCache2" },
    { text="📖 คัมภีร์วิชา: 和光同尘", id="Gong4_Esoterica_2", cat="⚔ วิชาบ่มเพาะ", story="Xaou_BookProxy_021", sourceStory="BookShop_Gong_1", cache="ItemCache3" },
    { text="📖 ตำราล้ำค่ามังกรหงส์", id="Other_Esoterica_JiuHua", cat="⚔ วิชาบ่มเพาะ", story="Xaou_BookProxy_022", sourceStory="BookShop_Gong_1", cache="ItemCache4" },
    { text="📖 ⚙ คัมภีร์วิชา: 劫心咒", id="Gong8_Esoterica_12", cat="⚔ วิชาบ่มเพาะ", story="Xaou_BookProxy_023", sourceStory="BookShop_Gong_1", cache="ItemCache5" },
    { text="📖 ⚙ คัมภีร์วิชา: 星斗之眼", id="Gong8_Esoterica_13", cat="⚔ วิชาบ่มเพาะ", story="Xaou_BookProxy_024", sourceStory="BookShop_Gong_1", cache="ItemCache6" },
    { text="📖 ⚙ คัมภีร์วิชา: 洞心咒", id="Gong8_Esoterica_11", cat="⚔ วิชาบ่มเพาะ", story="Xaou_BookProxy_025", sourceStory="BookShop_Gong_1", cache="ItemCache7" },
    { text="📖 ⛰ คัมภีร์วิชา: 九幽返照", id="Gong5_Esoterica_5", cat="⚔ วิชาบ่มเพาะ", story="Xaou_BookProxy_026", sourceStory="BookShop_Gong_1", cache="ItemCache8" },
    { text="📖 ⛰ คัมภีร์วิชา: 五感之蚀", id="Gong5_Esoterica_2", cat="⚔ วิชาบ่มเพาะ", story="Xaou_BookProxy_027", sourceStory="BookShop_Gong_1", cache="ItemCache9" },
    { text="📖 ⛰ คัมภีร์วิชา: 偷天", id="Gong5_Esoterica_12", cat="⚔ วิชาบ่มเพาะ", story="Xaou_BookProxy_028", sourceStory="BookShop_Gong_1", cache="ItemCache10" },
    { text="📖 ⛰ คัมภีร์วิชา: 厚德篇", id="Gong11_Esoterica_9", cat="⚔ วิชาบ่มเพาะ", story="Xaou_BookProxy_029", sourceStory="BookShop_Gong_1", cache="ItemCache11" },
    { text="📖 ⛰ คัมภีร์วิชา: 地母玄经", id="Gong11_Esoterica_15", cat="⚔ วิชาบ่มเพาะ", story="Xaou_BookProxy_030", sourceStory="BookShop_Gong_1", cache="ItemCache12" },
    { text="📖 ⛰ คัมภีร์วิชา: 形容之蚀", id="Gong5_Esoterica_1", cat="⚔ วิชาบ่มเพาะ", story="Xaou_BookProxy_031", sourceStory="BookShop_Gong_1", cache="ItemCache13" },
    { text="📖 ⛰ คัมภีร์วิชา: 欺天", id="Gong5_Esoterica_10", cat="⚔ วิชาบ่มเพาะ", story="Xaou_BookProxy_032", sourceStory="BookShop_Gong_1", cache="ItemCache14" },
    { text="📖 ⛰ คัมภีร์วิชา: 气运之蚀", id="Gong5_Esoterica_4", cat="⚔ วิชาบ่มเพาะ", story="Xaou_BookProxy_033", sourceStory="BookShop_Gong_1", cache="ItemCache15" },
    { text="📖 ⛰ คัมภีร์วิชา: 灵视神观", id="Gong11_Esoterica_6", cat="⚔ วิชาบ่มเพาะ", story="Xaou_BookProxy_034", sourceStory="BookShop_Gong_1", cache="ItemCache16" },
    { text="📖 ⛰ คัมภีร์วิชา: 神智之蚀", id="Gong5_Esoterica_3", cat="⚔ วิชาบ่มเพาะ", story="Xaou_BookProxy_035", sourceStory="BookShop_Gong_1", cache="ItemCache17" },
    { text="📖 ⛰ คัมภีร์วิชา: 窃天", id="Gong5_Esoterica_11", cat="⚔ วิชาบ่มเพาะ", story="Xaou_BookProxy_036", sourceStory="BookShop_Gong_1", cache="ItemCache18" },
    { text="📖 ⛰ คัมภีร์วิชา: 蛰命法", id="Gong5_Esoterica_9", cat="⚔ วิชาบ่มเพาะ", story="Xaou_BookProxy_037", sourceStory="BookShop_Gong_1", cache="ItemCache19" },
    { text="📖 ⛰ คัมภีร์วิชา: 龟息诀", id="Gong5_Esoterica_8", cat="⚔ วิชาบ่มเพาะ", story="Xaou_BookProxy_038", sourceStory="BookShop_Gong_1", cache="ItemCache20" },
    { text="📖 ⛰ เคล็ดลับสืบทอดบันทึกสมบัติหนานกงข้ามเคราะห์", id="Other_Esoterica_ChiLianYuan1", cat="⚔ วิชาบ่มเพาะ", story="Xaou_BookProxy_039", sourceStory="BookShop_Gong_1", cache="ItemCache21" },
    { text="📖 ⛰ เทพธาตุวิชา", id="Gong11_Esoterica_8", cat="⚔ วิชาบ่มเพาะ", story="Xaou_BookProxy_040", sourceStory="BookShop_Gong_2", cache="ItemCache2" },
    { text="📖 ⛰ แปดขั้วหลอมรูปเคล็ด", id="Gong11_Esoterica_7", cat="⚔ วิชาบ่มเพาะ", story="Xaou_BookProxy_041", sourceStory="BookShop_Gong_2", cache="ItemCache3" },
    { text="📖 🌊 คัมภีร์วิชา: 紫霞丹霄", id="Other_Esoterica_DanXia2", cat="⚔ วิชาบ่มเพาะ", story="Xaou_BookProxy_042", sourceStory="BookShop_Gong_2", cache="ItemCache4" },
    { text="📖 🌊 รูปแท้วารีปราณ", id="Gong1_Esoterica_8", cat="⚔ วิชาบ่มเพาะ", story="Xaou_BookProxy_043", sourceStory="BookShop_Gong_2", cache="ItemCache5" },
    { text="📖 🌊 รูปแท้เทพวารี", id="Gong1_Esoterica_9", cat="⚔ วิชาบ่มเพาะ", story="Xaou_BookProxy_044", sourceStory="BookShop_Gong_2", cache="ItemCache6" },
    { text="📖 🌊 รูปแท้แก่นวารี", id="Gong1_Esoterica_7", cat="⚔ วิชาบ่มเพาะ", story="Xaou_BookProxy_045", sourceStory="BookShop_Gong_2", cache="ItemCache7" },
    { text="📖 🌊 วิชาชำระใจห้าธารา", id="Gong1_Esoterica_1", cat="⚔ วิชาบ่มเพาะ", story="Xaou_BookProxy_046", sourceStory="BookShop_Gong_2", cache="ItemCache8" },
    { text="📖 🌊 วิชาใจธารบิน", id="Other_Esoterica_LongHu2", cat="⚔ วิชาบ่มเพาะ", story="Xaou_BookProxy_047", sourceStory="BookShop_Gong_2", cache="ItemCache9" },
    { text="📖 🌊 เคล็ดธารเชี่ยว", id="Gong1_Esoterica_5", cat="⚔ วิชาบ่มเพาะ", story="Xaou_BookProxy_048", sourceStory="BookShop_Gong_2", cache="ItemCache10" },
    { text="📖 🌳 คัมภีร์วิชา: 三世洞真法", id="Gong9_Esoterica_2", cat="⚔ วิชาบ่มเพาะ", story="Xaou_BookProxy_049", sourceStory="BookShop_Gong_2", cache="ItemCache11" },
    { text="📖 🌳 คัมภีร์วิชา: 修罗之体·一阶", id="Gong9_Esoterica_14", cat="⚔ วิชาบ่มเพาะ", story="Xaou_BookProxy_050", sourceStory="BookShop_Gong_2", cache="ItemCache12" },
    { text="📖 🌳 คัมภีร์วิชา: 养身法", id="Gong9_Esoterica_7", cat="⚔ วิชาบ่มเพาะ", story="Xaou_BookProxy_051", sourceStory="BookShop_Gong_2", cache="ItemCache13" },
    { text="📖 🌳 คัมภีร์วิชา: 神截经", id="Gong9_Esoterica_11", cat="⚔ วิชาบ่มเพาะ", story="Xaou_BookProxy_052", sourceStory="BookShop_Gong_2", cache="ItemCache14" },
    { text="📖 🌳 คัมภีร์วิชา: 胎化易形", id="Gong9_Esoterica_10", cat="⚔ วิชาบ่มเพาะ", story="Xaou_BookProxy_053", sourceStory="BookShop_Gong_2", cache="ItemCache15" },
    { text="📖 🌳 คัมภีร์วิชา: 轮回心眼", id="Gong9_Esoterica_1", cat="⚔ วิชาบ่มเพาะ", story="Xaou_BookProxy_054", sourceStory="BookShop_Gong_2", cache="ItemCache16" },
    { text="📖 🌳 ปราณแท้ซ่างชิง", id="Gong2_Esoterica_6", cat="⚔ วิชาบ่มเพาะ", story="Xaou_BookProxy_055", sourceStory="BookShop_Gong_2", cache="ItemCache17" },
    { text="📖 🔥 คัมภีร์วิชา: 五内蕴火", id="Gong10_Esoterica_6", cat="⚔ วิชาบ่มเพาะ", story="Xaou_BookProxy_056", sourceStory="BookShop_Gong_2", cache="ItemCache18" },
    { text="📖 🔥 คัมภีร์วิชา: 净火灼心", id="Gong10_Esoterica_10", cat="⚔ วิชาบ่มเพาะ", story="Xaou_BookProxy_057", sourceStory="BookShop_Gong_2", cache="ItemCache19" },
    { text="📖 🔥 คัมภีร์วิชา: 天火同人", id="Gong10_Esoterica_11", cat="⚔ วิชาบ่มเพาะ", story="Xaou_BookProxy_058", sourceStory="BookShop_Gong_2", cache="ItemCache20" },
    { text="📖 🔥 คัมภีร์วิชา: 太上内经", id="Gong6_Esoterica_14", cat="⚔ วิชาบ่มเพาะ", story="Xaou_BookProxy_059", sourceStory="BookShop_Gong_2", cache="ItemCache21" },
    { text="📖 🔥 คัมภีร์วิชา: 太上忘情", id="Gong7_Esoterica_4", cat="⚔ วิชาบ่มเพาะ", story="Xaou_BookProxy_060", sourceStory="BookShop_Gong_3", cache="ItemCache2" },
    { text="📖 🔥 คัมภีร์วิชา: 寄情之术", id="Gong7_Esoterica_2", cat="⚔ วิชาบ่มเพาะ", story="Xaou_BookProxy_061", sourceStory="BookShop_Gong_3", cache="ItemCache3" },
    { text="📖 🔥 คัมภีร์วิชา: 心斋", id="Gong7_Esoterica_1", cat="⚔ วิชาบ่มเพาะ", story="Xaou_BookProxy_062", sourceStory="BookShop_Gong_3", cache="ItemCache4" },
    { text="📖 🔥 คัมภีร์วิชา: 明目诀", id="Gong6_Esoterica_7", cat="⚔ วิชาบ่มเพาะ", story="Xaou_BookProxy_063", sourceStory="BookShop_Gong_3", cache="ItemCache5" },
    { text="📖 🔥 คัมภีร์วิชา: 洗心咒", id="Gong6_Esoterica_2", cat="⚔ วิชาบ่มเพาะ", story="Xaou_BookProxy_064", sourceStory="BookShop_Gong_3", cache="ItemCache6" },
    { text="📖 🔥 คัมภีร์วิชา: 脱胎换骨", id="Gong7_Esoterica_5", cat="⚔ วิชาบ่มเพาะ", story="Xaou_BookProxy_065", sourceStory="BookShop_Gong_3", cache="ItemCache7" },
    { text="📖 🔥 คัมภีร์วิชา: 菁华诀", id="Gong6_Esoterica_12", cat="⚔ วิชาบ่มเพาะ", story="Xaou_BookProxy_066", sourceStory="BookShop_Gong_3", cache="ItemCache8" },
    { text="📖 🔥 คัมภีร์วิชา: 道德清净法", id="Gong6_Esoterica_3", cat="⚔ วิชาบ่มเพาะ", story="Xaou_BookProxy_067", sourceStory="BookShop_Gong_3", cache="ItemCache9" },
    { text="📖 🔥 คัมภีร์วิชา: 长生诀", id="Gong7_Esoterica_8", cat="⚔ วิชาบ่มเพาะ", story="Xaou_BookProxy_068", sourceStory="BookShop_Gong_3", cache="ItemCache10" },
    { text="📖 🔥 วิชาแปรชะตากลสวรรค์", id="Other_Esoterica_XuanKong", cat="⚔ วิชาบ่มเพาะ", story="Xaou_BookProxy_069", sourceStory="BookShop_Gong_3", cache="ItemCache11" },
    { text="📖 กลั่นฮวงจุ้ย", id="Gong1_LvUpEsoterica_9", cat="⬆ ตำราเลื่อนวิชา", story="Xaou_BookProxy_070", sourceStory="BookShop_GongLvUp_1", cache="ItemCache2" },
    { text="📖 ดาวเหนือแดนกระบี่", id="Gong8_LvUpEsoterica_9", cat="⬆ ตำราเลื่อนวิชา", story="Xaou_BookProxy_071", sourceStory="BookShop_GongLvUp_1", cache="ItemCache3" },
    { text="📖 ตำราเลื่อนวิชา: 万法归藏", id="Gong4_LvUpEsoterica_3", cat="⬆ ตำราเลื่อนวิชา", story="Xaou_BookProxy_072", sourceStory="BookShop_GongLvUp_1", cache="ItemCache4" },
    { text="📖 ตำราเลื่อนวิชา: 万法归藏", id="Gong4_LvUpEsoterica_4", cat="⬆ ตำราเลื่อนวิชา", story="Xaou_BookProxy_073", sourceStory="BookShop_GongLvUp_1", cache="ItemCache5" },
    { text="📖 ตำราเลื่อนวิชา: 万法归藏", id="Gong4_LvUpEsoterica_5", cat="⬆ ตำราเลื่อนวิชา", story="Xaou_BookProxy_074", sourceStory="BookShop_GongLvUp_1", cache="ItemCache6" },
    { text="📖 ตำราเลื่อนวิชา: 东木分神书", id="Gong12_LvUpEsoterica_5", cat="⬆ ตำราเลื่อนวิชา", story="Xaou_BookProxy_075", sourceStory="BookShop_GongLvUp_1", cache="ItemCache7" },
    { text="📖 ตำราเลื่อนวิชา: 东木分神书", id="Gong12_LvUpEsoterica_6", cat="⬆ ตำราเลื่อนวิชา", story="Xaou_BookProxy_076", sourceStory="BookShop_GongLvUp_1", cache="ItemCache8" },
    { text="📖 ตำราเลื่อนวิชา: 东木分神书", id="Gong12_LvUpEsoterica_7", cat="⬆ ตำราเลื่อนวิชา", story="Xaou_BookProxy_077", sourceStory="BookShop_GongLvUp_1", cache="ItemCache9" },
    { text="📖 ตำราเลื่อนวิชา: 九幽炼神", id="Gong11_LvUpEsoterica_4", cat="⬆ ตำราเลื่อนวิชา", story="Xaou_BookProxy_078", sourceStory="BookShop_GongLvUp_1", cache="ItemCache10" },
    { text="📖 ตำราเลื่อนวิชา: 元央归息法", id="Gong9_LvUpEsoterica_3", cat="⬆ ตำราเลื่อนวิชา", story="Xaou_BookProxy_079", sourceStory="BookShop_GongLvUp_1", cache="ItemCache11" },
    { text="📖 ตำราเลื่อนวิชา: 六道轮回丹", id="Gong9_LvUpEsoterica_2", cat="⬆ ตำราเลื่อนวิชา", story="Xaou_BookProxy_080", sourceStory="BookShop_GongLvUp_1", cache="ItemCache12" },
    { text="📖 ตำราเลื่อนวิชา: 天甲符", id="Gong12_LvUpEsoterica_2", cat="⬆ ตำราเลื่อนวิชา", story="Xaou_BookProxy_081", sourceStory="BookShop_GongLvUp_1", cache="ItemCache13" },
    { text="📖 ตำราเลื่อนวิชา: 如意幻境", id="Gong7_LvUpEsoterica_3", cat="⬆ ตำราเลื่อนวิชา", story="Xaou_BookProxy_082", sourceStory="BookShop_GongLvUp_1", cache="ItemCache14" },
    { text="📖 ตำราเลื่อนวิชา: 秘宝：偷天七绝针", id="Gong5_LvUpEsoterica_8", cat="⬆ ตำราเลื่อนวิชา", story="Xaou_BookProxy_083", sourceStory="BookShop_GongLvUp_1", cache="ItemCache15" },
    { text="📖 ตำราเลื่อนวิชา: 秘宝：天权剑", id="Gong8_LvUpEsoterica_15", cat="⬆ ตำราเลื่อนวิชา", story="Xaou_BookProxy_084", sourceStory="BookShop_GongLvUp_1", cache="ItemCache16" },
    { text="📖 ตำราเลื่อนวิชา: 秘宝：天枢剑", id="Gong8_LvUpEsoterica_12", cat="⬆ ตำราเลื่อนวิชา", story="Xaou_BookProxy_085", sourceStory="BookShop_GongLvUp_1", cache="ItemCache17" },
    { text="📖 ตำราเลื่อนวิชา: 秘宝：天玑剑", id="Gong8_LvUpEsoterica_14", cat="⬆ ตำราเลื่อนวิชา", story="Xaou_BookProxy_086", sourceStory="BookShop_GongLvUp_1", cache="ItemCache18" },
    { text="📖 ตำราเลื่อนวิชา: 秘宝：天璇剑", id="Gong8_LvUpEsoterica_13", cat="⬆ ตำราเลื่อนวิชา", story="Xaou_BookProxy_087", sourceStory="BookShop_GongLvUp_1", cache="ItemCache19" },
    { text="📖 ตำราเลื่อนวิชา: 秘宝：开阳剑", id="Gong8_LvUpEsoterica_17", cat="⬆ ตำราเลื่อนวิชา", story="Xaou_BookProxy_088", sourceStory="BookShop_GongLvUp_1", cache="ItemCache20" },
    { text="📖 ตำราเลื่อนวิชา: 秘宝：戊己杏黄旗", id="Gong4_LvUpEsoterica_11", cat="⬆ ตำราเลื่อนวิชา", story="Xaou_BookProxy_089", sourceStory="BookShop_GongLvUp_1", cache="ItemCache21" },
    { text="📖 ตำราเลื่อนวิชา: 秘宝：摇光剑", id="Gong8_LvUpEsoterica_18", cat="⬆ ตำราเลื่อนวิชา", story="Xaou_BookProxy_090", sourceStory="BookShop_GongLvUp_2", cache="ItemCache2" },
    { text="📖 ตำราเลื่อนวิชา: 秘宝：清宁飞羽", id="Gong7_LvUpEsoterica_7", cat="⬆ ตำราเลื่อนวิชา", story="Xaou_BookProxy_091", sourceStory="BookShop_GongLvUp_2", cache="ItemCache3" },
    { text="📖 ตำราเลื่อนวิชา: 秘宝：玉衡剑", id="Gong8_LvUpEsoterica_16", cat="⬆ ตำราเลื่อนวิชา", story="Xaou_BookProxy_092", sourceStory="BookShop_GongLvUp_2", cache="ItemCache4" },
    { text="📖 ตำราเลื่อนวิชา: 秘宝：百灵斩仙剑", id="Gong3_LvUpEsoterica_10", cat="⬆ ตำราเลื่อนวิชา", story="Xaou_BookProxy_093", sourceStory="BookShop_GongLvUp_2", cache="ItemCache5" },
    { text="📖 ตำราเลื่อนวิชา: 秘宝：神农鼎", id="Gong6_LvUpEsoterica_7", cat="⬆ ตำราเลื่อนวิชา", story="Xaou_BookProxy_094", sourceStory="BookShop_GongLvUp_2", cache="ItemCache6" },
    { text="📖 ตำราเลื่อนวิชา: 秘宝：离地焰光旗", id="Gong6_LvUpEsoterica_8", cat="⬆ ตำราเลื่อนวิชา", story="Xaou_BookProxy_095", sourceStory="BookShop_GongLvUp_2", cache="ItemCache7" },
    { text="📖 ตำราเลื่อนวิชา: 遮天符", id="Gong12_LvUpEsoterica_4", cat="⬆ ตำราเลื่อนวิชา", story="Xaou_BookProxy_096", sourceStory="BookShop_GongLvUp_2", cache="ItemCache8" },
    { text="📖 ลับสมบัติ：หนึ่งกระบี่", id="Gong11_LvUpEsoterica_13", cat="⬆ ตำราเลื่อนวิชา", story="Xaou_BookProxy_097", sourceStory="BookShop_GongLvUp_2", cache="ItemCache9" },
    { text="📖 เก้าหยางเทพอัคคีแดน", id="Gong10_LvUpEsoterica_4", cat="⬆ ตำราเลื่อนวิชา", story="Xaou_BookProxy_098", sourceStory="BookShop_GongLvUp_2", cache="ItemCache10" },
    { text="📖 เทพกระบี่ยันต์", id="Gong12_LvUpEsoterica_1", cat="⬆ ตำราเลื่อนวิชา", story="Xaou_BookProxy_099", sourceStory="BookShop_GongLvUp_2", cache="ItemCache11" },
    { text="📖 เทพมนต์ยันต์", id="Gong12_LvUpEsoterica_3", cat="⬆ ตำราเลื่อนวิชา", story="Xaou_BookProxy_100", sourceStory="BookShop_GongLvUp_2", cache="ItemCache12" },
    { text="📖 แดนวารีแท้เก้าหยิน", id="Gong1_LvUpEsoterica_6", cat="⬆ ตำราเลื่อนวิชา", story="Xaou_BookProxy_101", sourceStory="BookShop_GongLvUp_2", cache="ItemCache13" },
    { text="📖 แสงเทพแม่เหล็กทำลายล้าง", id="Gong4_LvUpEsoterica_1", cat="⬆ ตำราเลื่อนวิชา", story="Xaou_BookProxy_102", sourceStory="BookShop_GongLvUp_2", cache="ItemCache14" },
    { text="📖 ⚙ กระบี่วิญญาณ", id="Gong3_LvUpEsoterica_5", cat="⬆ ตำราเลื่อนวิชา", story="Xaou_BookProxy_103", sourceStory="BookShop_GongLvUp_2", cache="ItemCache15" },
    { text="📖 ⚙ ขั้วกระบี่·สอง", id="Gong3_LvUpEsoterica_6", cat="⬆ ตำราเลื่อนวิชา", story="Xaou_BookProxy_104", sourceStory="BookShop_GongLvUp_2", cache="ItemCache16" },
    { text="📖 ⚙ ขั้วกระบี่·สาม", id="Gong3_LvUpEsoterica_8", cat="⬆ ตำราเลื่อนวิชา", story="Xaou_BookProxy_105", sourceStory="BookShop_GongLvUp_2", cache="ItemCache17" },
    { text="📖 ⚙ ควบคุมกระบี่วิชา", id="Gong3_LvUpEsoterica_3", cat="⬆ ตำราเลื่อนวิชา", story="Xaou_BookProxy_106", sourceStory="BookShop_GongLvUp_2", cache="ItemCache18" },
    { text="📖 ⚙ ควบคุมกระบี่วิชา", id="Gong3_LvUpEsoterica_4", cat="⬆ ตำราเลื่อนวิชา", story="Xaou_BookProxy_107", sourceStory="BookShop_GongLvUp_2", cache="ItemCache19" },
    { text="📖 ⚙ ตำราเลื่อนวิชา: 天权剑意", id="Gong8_LvUpEsoterica_4", cat="⬆ ตำราเลื่อนวิชา", story="Xaou_BookProxy_108", sourceStory="BookShop_GongLvUp_2", cache="ItemCache20" },
    { text="📖 ⚙ ตำราเลื่อนวิชา: 天枢剑意", id="Gong8_LvUpEsoterica_1", cat="⬆ ตำราเลื่อนวิชา", story="Xaou_BookProxy_109", sourceStory="BookShop_GongLvUp_2", cache="ItemCache21" },
    { text="📖 ⚙ ตำราเลื่อนวิชา: 天玑剑意", id="Gong8_LvUpEsoterica_3", cat="⬆ ตำราเลื่อนวิชา", story="Xaou_BookProxy_110", sourceStory="BookShop_GongLvUp_3", cache="ItemCache2" },
    { text="📖 ⚙ ตำราเลื่อนวิชา: 天璇剑意", id="Gong8_LvUpEsoterica_2", cat="⬆ ตำราเลื่อนวิชา", story="Xaou_BookProxy_111", sourceStory="BookShop_GongLvUp_3", cache="ItemCache3" },
    { text="📖 ⚙ ตำราเลื่อนวิชา: 庚金元神·圆满", id="Gong4_LvUpEsoterica_6", cat="⬆ ตำราเลื่อนวิชา", story="Xaou_BookProxy_112", sourceStory="BookShop_GongLvUp_3", cache="ItemCache4" },
    { text="📖 ⚙ ตำราเลื่อนวิชา: 开阳剑意", id="Gong8_LvUpEsoterica_6", cat="⬆ ตำราเลื่อนวิชา", story="Xaou_BookProxy_113", sourceStory="BookShop_GongLvUp_3", cache="ItemCache5" },
    { text="📖 ⚙ ตำราเลื่อนวิชา: 我剑·三", id="Gong3_LvUpEsoterica_9", cat="⬆ ตำราเลื่อนวิชา", story="Xaou_BookProxy_114", sourceStory="BookShop_GongLvUp_3", cache="ItemCache6" },
    { text="📖 ⚙ ตำราเลื่อนวิชา: 我剑·二", id="Gong3_LvUpEsoterica_7", cat="⬆ ตำราเลื่อนวิชา", story="Xaou_BookProxy_115", sourceStory="BookShop_GongLvUp_3", cache="ItemCache7" },
    { text="📖 ⚙ ตำราเลื่อนวิชา: 摇光剑意", id="Gong8_LvUpEsoterica_7", cat="⬆ ตำราเลื่อนวิชา", story="Xaou_BookProxy_116", sourceStory="BookShop_GongLvUp_3", cache="ItemCache8" },
    { text="📖 ⚙ ตำราเลื่อนวิชา: 杀意", id="Gong3_LvUpEsoterica_1", cat="⬆ ตำราเลื่อนวิชา", story="Xaou_BookProxy_117", sourceStory="BookShop_GongLvUp_3", cache="ItemCache9" },
    { text="📖 ⚙ ตำราเลื่อนวิชา: 杀意", id="Gong3_LvUpEsoterica_2", cat="⬆ ตำราเลื่อนวิชา", story="Xaou_BookProxy_118", sourceStory="BookShop_GongLvUp_3", cache="ItemCache10" },
    { text="📖 ⚙ ตำราเลื่อนวิชา: 玉衡剑意", id="Gong8_LvUpEsoterica_5", cat="⬆ ตำราเลื่อนวิชา", story="Xaou_BookProxy_119", sourceStory="BookShop_GongLvUp_3", cache="ItemCache11" },
    { text="📖 ⚙ ตำราเลื่อนวิชา: 赦心咒", id="Gong8_LvUpEsoterica_8", cat="⬆ ตำราเลื่อนวิชา", story="Xaou_BookProxy_120", sourceStory="BookShop_GongLvUp_3", cache="ItemCache12" },
    { text="📖 ⚙ ท่าสุดยอดดาวเหนือ-กระบี่ขั้วเหนือ", id="Gong8_LvUpEsoterica_10", cat="⬆ ตำราเลื่อนวิชา", story="Xaou_BookProxy_121", sourceStory="BookShop_GongLvUp_3", cache="ItemCache13" },
    { text="📖 ⚙ ท่าสุดยอดดาวเหนือ-กระบี่คืนหนึ่ง", id="Gong8_LvUpEsoterica_11", cat="⬆ ตำราเลื่อนวิชา", story="Xaou_BookProxy_122", sourceStory="BookShop_GongLvUp_3", cache="ItemCache14" },
    { text="📖 ⛰ คุนต้นกำเนิดแท้ปราณ", id="Gong11_LvUpEsoterica_10", cat="⬆ ตำราเลื่อนวิชา", story="Xaou_BookProxy_123", sourceStory="BookShop_GongLvUp_3", cache="ItemCache15" },
    { text="📖 ⛰ คุนต้นกำเนิดแท้ปราณ", id="Gong11_LvUpEsoterica_11", cat="⬆ ตำราเลื่อนวิชา", story="Xaou_BookProxy_124", sourceStory="BookShop_GongLvUp_3", cache="ItemCache16" },
    { text="📖 ⛰ คุนต้นกำเนิดแท้ปราณ", id="Gong11_LvUpEsoterica_9", cat="⬆ ตำราเลื่อนวิชา", story="Xaou_BookProxy_125", sourceStory="BookShop_GongLvUp_3", cache="ItemCache17" },
    { text="📖 ⛰ ตำราเลื่อนวิชา: 五感返照", id="Gong5_LvUpEsoterica_2", cat="⬆ ตำราเลื่อนวิชา", story="Xaou_BookProxy_126", sourceStory="BookShop_GongLvUp_3", cache="ItemCache18" },
    { text="📖 ⛰ ตำราเลื่อนวิชา: 凝血神盾", id="Gong5_LvUpEsoterica_6", cat="⬆ ตำราเลื่อนวิชา", story="Xaou_BookProxy_127", sourceStory="BookShop_GongLvUp_3", cache="ItemCache19" },
    { text="📖 ⛰ ตำราเลื่อนวิชา: 太虚神盾", id="Gong11_LvUpEsoterica_5", cat="⬆ ตำราเลื่อนวิชา", story="Xaou_BookProxy_128", sourceStory="BookShop_GongLvUp_3", cache="ItemCache20" },
    { text="📖 ⛰ ตำราเลื่อนวิชา: 少阴诀", id="Gong11_LvUpEsoterica_6", cat="⬆ ตำราเลื่อนวิชา", story="Xaou_BookProxy_129", sourceStory="BookShop_GongLvUp_3", cache="ItemCache21" },
    { text="📖 ⛰ ตำราเลื่อนวิชา: 少阴锻体", id="Gong11_LvUpEsoterica_1", cat="⬆ ตำราเลื่อนวิชา", story="Xaou_BookProxy_130", sourceStory="BookShop_GongLvUp_4", cache="ItemCache2" },
    { text="📖 ⛰ ตำราเลื่อนวิชา: 幽狱诀", id="Gong11_LvUpEsoterica_8", cat="⬆ ตำราเลื่อนวิชา", story="Xaou_BookProxy_131", sourceStory="BookShop_GongLvUp_4", cache="ItemCache3" },
    { text="📖 ⛰ ตำราเลื่อนวิชา: 形容返照", id="Gong5_LvUpEsoterica_1", cat="⬆ ตำราเลื่อนวิชา", story="Xaou_BookProxy_132", sourceStory="BookShop_GongLvUp_4", cache="ItemCache4" },
    { text="📖 ⛰ ตำราเลื่อนวิชา: 戊土元神·圆满", id="Gong4_LvUpEsoterica_10", cat="⬆ ตำราเลื่อนวิชา", story="Xaou_BookProxy_133", sourceStory="BookShop_GongLvUp_4", cache="ItemCache5" },
    { text="📖 ⛰ ตำราเลื่อนวิชา: 换日", id="Gong5_LvUpEsoterica_7", cat="⬆ ตำราเลื่อนวิชา", story="Xaou_BookProxy_134", sourceStory="BookShop_GongLvUp_4", cache="ItemCache6" },
    { text="📖 ⛰ ตำราเลื่อนวิชา: 气运返照", id="Gong5_LvUpEsoterica_4", cat="⬆ ตำราเลื่อนวิชา", story="Xaou_BookProxy_135", sourceStory="BookShop_GongLvUp_4", cache="ItemCache7" },
    { text="📖 ⛰ ตำราเลื่อนวิชา: 浊之躯", id="Gong5_LvUpEsoterica_5", cat="⬆ ตำราเลื่อนวิชา", story="Xaou_BookProxy_136", sourceStory="BookShop_GongLvUp_4", cache="ItemCache8" },
    { text="📖 ⛰ ตำราเลื่อนวิชา: 玄阴锻体", id="Gong11_LvUpEsoterica_2", cat="⬆ ตำราเลื่อนวิชา", story="Xaou_BookProxy_137", sourceStory="BookShop_GongLvUp_4", cache="ItemCache9" },
    { text="📖 ⛰ ตำราเลื่อนวิชา: 瞬形法", id="Gong11_LvUpEsoterica_3", cat="⬆ ตำราเลื่อนวิชา", story="Xaou_BookProxy_138", sourceStory="BookShop_GongLvUp_4", cache="ItemCache10" },
    { text="📖 ⛰ ตำราเลื่อนวิชา: 神智返照", id="Gong5_LvUpEsoterica_3", cat="⬆ ตำราเลื่อนวิชา", story="Xaou_BookProxy_139", sourceStory="BookShop_GongLvUp_4", cache="ItemCache11" },
    { text="📖 ⛰ ลี้ลับหยินเคล็ด", id="Gong11_LvUpEsoterica_7", cat="⬆ ตำราเลื่อนวิชา", story="Xaou_BookProxy_140", sourceStory="BookShop_GongLvUp_4", cache="ItemCache12" },
    { text="📖 ⛰ หนึ่งกระบี่", id="Gong11_LvUpEsoterica_12", cat="⬆ ตำราเลื่อนวิชา", story="Xaou_BookProxy_141", sourceStory="BookShop_GongLvUp_4", cache="ItemCache13" },
    { text="📖 🌊 ตำราเลื่อนวิชา: 壬水元神·圆满", id="Gong4_LvUpEsoterica_8", cat="⬆ ตำราเลื่อนวิชา", story="Xaou_BookProxy_142", sourceStory="BookShop_GongLvUp_4", cache="ItemCache14" },
    { text="📖 🌊 ตำราเลื่อนวิชา: 玉清定境", id="Gong4_LvUpEsoterica_2", cat="⬆ ตำราเลื่อนวิชา", story="Xaou_BookProxy_143", sourceStory="BookShop_GongLvUp_4", cache="ItemCache15" },
    { text="📖 🌊 รวมกระแสกังซา", id="Gong1_LvUpEsoterica_7", cat="⬆ ตำราเลื่อนวิชา", story="Xaou_BookProxy_144", sourceStory="BookShop_GongLvUp_4", cache="ItemCache16" },
    { text="📖 🌊 รวมกระแสกังซา", id="Gong1_LvUpEsoterica_8", cat="⬆ ตำราเลื่อนวิชา", story="Xaou_BookProxy_145", sourceStory="BookShop_GongLvUp_4", cache="ItemCache17" },
    { text="📖 🌊 วิชาแท้เอกสวรรค์", id="Gong1_LvUpEsoterica_2", cat="⬆ ตำราเลื่อนวิชา", story="Xaou_BookProxy_146", sourceStory="BookShop_GongLvUp_4", cache="ItemCache18" },
    { text="📖 🌊 สมาธิกระจกวารีมองใจ", id="Gong1_LvUpEsoterica_3", cat="⬆ ตำราเลื่อนวิชา", story="Xaou_BookProxy_147", sourceStory="BookShop_GongLvUp_4", cache="ItemCache19" },
    { text="📖 🌊 หมื่นพฤกษาคืนวสันต์", id="Gong9_LvUpEsoterica_1", cat="⬆ ตำราเลื่อนวิชา", story="Xaou_BookProxy_148", sourceStory="BookShop_GongLvUp_4", cache="ItemCache20" },
    { text="📖 🌊 เคล็ดคืนทะเล", id="Gong1_LvUpEsoterica_5", cat="⬆ ตำราเลื่อนวิชา", story="Xaou_BookProxy_149", sourceStory="BookShop_GongLvUp_4", cache="ItemCache21" },
    { text="📖 🌊 เคล็ดฝนสวรรค์", id="Gong1_LvUpEsoterica_1", cat="⬆ ตำราเลื่อนวิชา", story="Xaou_BookProxy_150", sourceStory="BookShop_GongLvUp_5", cache="ItemCache2" },
    { text="📖 🌊 เคล็ดร่วมวายุ", id="Gong1_LvUpEsoterica_4", cat="⬆ ตำราเลื่อนวิชา", story="Xaou_BookProxy_151", sourceStory="BookShop_GongLvUp_5", cache="ItemCache3" },
    { text="📖 🌳 ตำราเลื่อนวิชา: 不昧真灵", id="Gong9_LvUpEsoterica_4", cat="⬆ ตำราเลื่อนวิชา", story="Xaou_BookProxy_152", sourceStory="BookShop_GongLvUp_5", cache="ItemCache4" },
    { text="📖 🌳 ตำราเลื่อนวิชา: 修罗之体·三阶", id="Gong9_LvUpEsoterica_11", cat="⬆ ตำราเลื่อนวิชา", story="Xaou_BookProxy_153", sourceStory="BookShop_GongLvUp_5", cache="ItemCache5" },
    { text="📖 🌳 ตำราเลื่อนวิชา: 修罗之体·二阶", id="Gong9_LvUpEsoterica_8", cat="⬆ ตำราเลื่อนวิชา", story="Xaou_BookProxy_154", sourceStory="BookShop_GongLvUp_5", cache="ItemCache6" },
    { text="📖 🌳 ตำราเลื่อนวิชา: 天人之体·三阶", id="Gong9_LvUpEsoterica_9", cat="⬆ ตำราเลื่อนวิชา", story="Xaou_BookProxy_155", sourceStory="BookShop_GongLvUp_5", cache="ItemCache7" },
    { text="📖 🌳 ตำราเลื่อนวิชา: 天人之体·二阶", id="Gong9_LvUpEsoterica_6", cat="⬆ ตำราเลื่อนวิชา", story="Xaou_BookProxy_156", sourceStory="BookShop_GongLvUp_5", cache="ItemCache8" },
    { text="📖 🌳 ตำราเลื่อนวิชา: 甲木元神·圆满", id="Gong4_LvUpEsoterica_7", cat="⬆ ตำราเลื่อนวิชา", story="Xaou_BookProxy_157", sourceStory="BookShop_GongLvUp_5", cache="ItemCache9" },
    { text="📖 🌳 ตำราเลื่อนวิชา: 真吾之体·三阶", id="Gong9_LvUpEsoterica_10", cat="⬆ ตำราเลื่อนวิชา", story="Xaou_BookProxy_158", sourceStory="BookShop_GongLvUp_5", cache="ItemCache10" },
    { text="📖 🌳 ตำราเลื่อนวิชา: 真吾之体·二阶", id="Gong9_LvUpEsoterica_7", cat="⬆ ตำราเลื่อนวิชา", story="Xaou_BookProxy_159", sourceStory="BookShop_GongLvUp_5", cache="ItemCache11" },
    { text="📖 🌳 ตำราเลื่อนวิชา: 神火合一·上清", id="Gong2_LvUpEsoterica_7", cat="⬆ ตำราเลื่อนวิชา", story="Xaou_BookProxy_160", sourceStory="BookShop_GongLvUp_5", cache="ItemCache12" },
    { text="📖 🌳 ตำราเลื่อนวิชา: 神火合一·心焰", id="Gong2_LvUpEsoterica_8", cat="⬆ ตำราเลื่อนวิชา", story="Xaou_BookProxy_161", sourceStory="BookShop_GongLvUp_5", cache="ItemCache13" },
    { text="📖 🌳 ปราณแท้ซ่างชิง", id="Gong2_LvUpEsoterica_5", cat="⬆ ตำราเลื่อนวิชา", story="Xaou_BookProxy_162", sourceStory="BookShop_GongLvUp_5", cache="ItemCache14" },
    { text="📖 🌳 ย้อนวัฏสงสาร·ลับ", id="Gong9_LvUpEsoterica_5", cat="⬆ ตำราเลื่อนวิชา", story="Xaou_BookProxy_163", sourceStory="BookShop_GongLvUp_5", cache="ItemCache15" },
    { text="📖 🌳 เคล็ดร้อยหลอม", id="Gong2_LvUpEsoterica_1", cat="⬆ ตำราเลื่อนวิชา", story="Xaou_BookProxy_164", sourceStory="BookShop_GongLvUp_5", cache="ItemCache16" },
    { text="📖 🌳 เคล็ดร้อยหลอม", id="Gong2_LvUpEsoterica_2", cat="⬆ ตำราเลื่อนวิชา", story="Xaou_BookProxy_165", sourceStory="BookShop_GongLvUp_5", cache="ItemCache17" },
    { text="📖 🌳 เคล็ดร้อยหลอม", id="Gong2_LvUpEsoterica_4", cat="⬆ ตำราเลื่อนวิชา", story="Xaou_BookProxy_166", sourceStory="BookShop_GongLvUp_5", cache="ItemCache18" },
    { text="📖 🔥 ตำราเลื่อนวิชา: 丙火元神·圆满", id="Gong4_LvUpEsoterica_9", cat="⬆ ตำราเลื่อนวิชา", story="Xaou_BookProxy_167", sourceStory="BookShop_GongLvUp_5", cache="ItemCache19" },
    { text="📖 🔥 ตำราเลื่อนวิชา: 五内蕴火", id="Gong10_LvUpEsoterica_1", cat="⬆ ตำราเลื่อนวิชา", story="Xaou_BookProxy_168", sourceStory="BookShop_GongLvUp_5", cache="ItemCache20" },
    { text="📖 🔥 ตำราเลื่อนวิชา: 五内蕴火", id="Gong10_LvUpEsoterica_2", cat="⬆ ตำราเลื่อนวิชา", story="Xaou_BookProxy_169", sourceStory="BookShop_GongLvUp_5", cache="ItemCache21" },
    { text="📖 🔥 ตำราเลื่อนวิชา: 天火同人", id="Gong10_LvUpEsoterica_7", cat="⬆ ตำราเลื่อนวิชา", story="Xaou_BookProxy_170", sourceStory="BookShop_GongLvUp_6", cache="ItemCache2" },
    { text="📖 🔥 ตำราเลื่อนวิชา: 太上忘情", id="Gong7_LvUpEsoterica_5", cat="⬆ ตำราเลื่อนวิชา", story="Xaou_BookProxy_171", sourceStory="BookShop_GongLvUp_6", cache="ItemCache3" },
    { text="📖 🔥 ตำราเลื่อนวิชา: 心斋", id="Gong7_LvUpEsoterica_1", cat="⬆ ตำราเลื่อนวิชา", story="Xaou_BookProxy_172", sourceStory="BookShop_GongLvUp_6", cache="ItemCache4" },
    { text="📖 🔥 ตำราเลื่อนวิชา: 心斋", id="Gong7_LvUpEsoterica_2", cat="⬆ ตำราเลื่อนวิชา", story="Xaou_BookProxy_173", sourceStory="BookShop_GongLvUp_6", cache="ItemCache5" },
    { text="📖 🔥 ตำราเลื่อนวิชา: 心炎", id="Gong10_LvUpEsoterica_5", cat="⬆ ตำราเลื่อนวิชา", story="Xaou_BookProxy_174", sourceStory="BookShop_GongLvUp_6", cache="ItemCache6" },
    { text="📖 🔥 ตำราเลื่อนวิชา: 斩念剑", id="Gong7_LvUpEsoterica_6", cat="⬆ ตำราเลื่อนวิชา", story="Xaou_BookProxy_175", sourceStory="BookShop_GongLvUp_6", cache="ItemCache7" },
    { text="📖 🔥 ตำราเลื่อนวิชา: 无漏之身", id="Gong6_LvUpEsoterica_2", cat="⬆ ตำราเลื่อนวิชา", story="Xaou_BookProxy_176", sourceStory="BookShop_GongLvUp_6", cache="ItemCache8" },
    { text="📖 🔥 ตำราเลื่อนวิชา: 火真之体", id="Gong10_LvUpEsoterica_6", cat="⬆ ตำราเลื่อนวิชา", story="Xaou_BookProxy_177", sourceStory="BookShop_GongLvUp_6", cache="ItemCache9" },
    { text="📖 🔥 ตำราเลื่อนวิชา: 炼身法-神", id="Gong6_LvUpEsoterica_6", cat="⬆ ตำราเลื่อนวิชา", story="Xaou_BookProxy_178", sourceStory="BookShop_GongLvUp_6", cache="ItemCache10" },
    { text="📖 🔥 ตำราเลื่อนวิชา: 炼身法-精", id="Gong6_LvUpEsoterica_5", cat="⬆ ตำราเลื่อนวิชา", story="Xaou_BookProxy_179", sourceStory="BookShop_GongLvUp_6", cache="ItemCache11" },
    { text="📖 🔥 ตำราเลื่อนวิชา: 炼身法-速", id="Gong6_LvUpEsoterica_4", cat="⬆ ตำราเลื่อนวิชา", story="Xaou_BookProxy_180", sourceStory="BookShop_GongLvUp_6", cache="ItemCache12" },
    { text="📖 🔥 ตำราเลื่อนวิชา: 焚日真法", id="Gong10_LvUpEsoterica_3", cat="⬆ ตำราเลื่อนวิชา", story="Xaou_BookProxy_181", sourceStory="BookShop_GongLvUp_6", cache="ItemCache13" },
    { text="📖 🔥 ตำราเลื่อนวิชา: 神火合一·雷泽", id="Gong2_LvUpEsoterica_6", cat="⬆ ตำราเลื่อนวิชา", story="Xaou_BookProxy_182", sourceStory="BookShop_GongLvUp_6", cache="ItemCache14" },
    { text="📖 🔥 ตำราเลื่อนวิชา: 长生诀", id="Gong7_LvUpEsoterica_4", cat="⬆ ตำราเลื่อนวิชา", story="Xaou_BookProxy_183", sourceStory="BookShop_GongLvUp_6", cache="ItemCache15" },
    { text="📖 🔥 เต๋าใจ", id="Gong6_LvUpEsoterica_3", cat="⬆ ตำราเลื่อนวิชา", story="Xaou_BookProxy_184", sourceStory="BookShop_GongLvUp_6", cache="ItemCache16" },
    { text="📖 🔥 ใหม่กายเคล็ด", id="Gong6_LvUpEsoterica_1", cat="⬆ ตำราเลื่อนวิชา", story="Xaou_BookProxy_185", sourceStory="BookShop_GongLvUp_6", cache="ItemCache17" },
    { text="📖 คัมภีร์บู๊ตึ้ง: 为道", id="Gong13_Esoterica_23", cat="☯ DLC บู๊ตึ้ง", story="Xaou_BookProxy_186", sourceStory="BookShop_WuDang_1", cache="ItemCache2" },
    { text="📖 คัมภีร์บู๊ตึ้ง: 纯阳无极功-正", id="Gong13_Esoterica_30", cat="☯ DLC บู๊ตึ้ง", story="Xaou_BookProxy_187", sourceStory="BookShop_WuDang_1", cache="ItemCache3" },
    { text="📖 คัมภีร์บู๊ตึ้ง: 纯阳无极功-逆", id="Gong13_Esoterica_31", cat="☯ DLC บู๊ตึ้ง", story="Xaou_BookProxy_188", sourceStory="BookShop_WuDang_1", cache="ItemCache4" },
    { text="📖 คัมภีร์บู๊ตึ้ง: 阴阳化御神遁", id="Gong13_Esoterica_29", cat="☯ DLC บู๊ตึ้ง", story="Xaou_BookProxy_189", sourceStory="BookShop_WuDang_1", cache="ItemCache5" },
    { text="📖 คัมภีร์เสวียนจี๋", id="Gong13_Esoterica_13", cat="☯ DLC บู๊ตึ้ง", story="Xaou_BookProxy_190", sourceStory="BookShop_WuDang_1", cache="ItemCache6" },
    { text="📖 คืนเต๋ากระบี่", id="Gong13_Esoterica_20", cat="☯ DLC บู๊ตึ้ง", story="Xaou_BookProxy_191", sourceStory="BookShop_WuDang_1", cache="ItemCache7" },
    { text="📖 จิตต้นกำเนิดหยินหยางเสวียนเทียน", id="Gong13_Esoterica_10", cat="☯ DLC บู๊ตึ้ง", story="Xaou_BookProxy_192", sourceStory="BookShop_WuDang_1", cache="ItemCache8" },
    { text="📖 ตำรากระบี่เจินอู่", id="Gong13_Esoterica_Fabao1", cat="☯ DLC บู๊ตึ้ง", story="Xaou_BookProxy_193", sourceStory="BookShop_WuDang_1", cache="ItemCache9" },
    { text="📖 ตำราหมื่นเต๋าจื่อเซียว", id="Gong13_Esoterica_Fabao2", cat="☯ DLC บู๊ตึ้ง", story="Xaou_BookProxy_194", sourceStory="BookShop_WuDang_1", cache="ItemCache10" },
    { text="📖 บันทึกลี้ลับไร้ขอบเขต", id="Gong13_Esoterica_6", cat="☯ DLC บู๊ตึ้ง", story="Xaou_BookProxy_195", sourceStory="BookShop_WuDang_1", cache="ItemCache11" },
    { text="📖 สูตรโอสถแท้ดาวเหนือ", id="Gong13_Esoterica_Dan", cat="☯ DLC บู๊ตึ้ง", story="Xaou_BookProxy_196", sourceStory="BookShop_WuDang_1", cache="ItemCache12" },
    { text="📖 หกเก้ากายเซียนสองลักษณ์", id="Gong13_Esoterica_9", cat="☯ DLC บู๊ตึ้ง", story="Xaou_BookProxy_197", sourceStory="BookShop_WuDang_1", cache="ItemCache13" },
    { text="📖 หนึ่งสัจธรรมหมื่นพิสดาร", id="Gong13_Esoterica_17", cat="☯ DLC บู๊ตึ้ง", story="Xaou_BookProxy_198", sourceStory="BookShop_WuDang_1", cache="ItemCache14" },
    { text="📖 เคล็ดควบคุมปราณหมุนเวียน", id="Gong13_Esoterica_16", cat="☯ DLC บู๊ตึ้ง", story="Xaou_BookProxy_199", sourceStory="BookShop_WuDang_1", cache="ItemCache15" },
    { text="📖 เบิกทัศน์ภายใน", id="Gong13_Esoterica_3", cat="☯ DLC บู๊ตึ้ง", story="Xaou_BookProxy_200", sourceStory="BookShop_WuDang_1", cache="ItemCache16" },
    { text="📖 ไร้หลีแท้วิชา", id="Gong13_Esoterica_26", cat="☯ DLC บู๊ตึ้ง", story="Xaou_BookProxy_201", sourceStory="BookShop_WuDang_1", cache="ItemCache17" },
    { text="📖 🌊 กระแสใจจันทรายิ่งใหญ่", id="Gong13_Esoterica_15", cat="☯ DLC บู๊ตึ้ง", story="Xaou_BookProxy_202", sourceStory="BookShop_WuDang_1", cache="ItemCache18" },
    { text="📖 🌊 คัมภีร์บู๊ตึ้ง: 为法", id="Gong13_Esoterica_22", cat="☯ DLC บู๊ตึ้ง", story="Xaou_BookProxy_203", sourceStory="BookShop_WuDang_1", cache="ItemCache19" },
    { text="📖 🌊 คัมภีร์บู๊ตึ้ง: 帝象剑", id="Gong13_Esoterica_19", cat="☯ DLC บู๊ตึ้ง", story="Xaou_BookProxy_204", sourceStory="BookShop_WuDang_1", cache="ItemCache20" },
    { text="📖 🌊 คัมภีร์บู๊ตึ้ง: 抱一法", id="Gong13_Esoterica_25", cat="☯ DLC บู๊ตึ้ง", story="Xaou_BookProxy_205", sourceStory="BookShop_WuDang_1", cache="ItemCache21" },
    { text="📖 🌊 คัมภีร์บู๊ตึ้ง: 潜云无形流", id="Gong13_Esoterica_28", cat="☯ DLC บู๊ตึ้ง", story="Xaou_BookProxy_206", sourceStory="BookShop_WuDang_2", cache="ItemCache2" },
    { text="📖 🌊 ตำรายันต์หยิน", id="Gong13_Esoterica_5", cat="☯ DLC บู๊ตึ้ง", story="Xaou_BookProxy_207", sourceStory="BookShop_WuDang_2", cache="ItemCache3" },
    { text="📖 🌊 วิชากลั่นความขุ่น", id="Gong13_Esoterica_2", cat="☯ DLC บู๊ตึ้ง", story="Xaou_BookProxy_208", sourceStory="BookShop_WuDang_2", cache="ItemCache4" },
    { text="📖 🌊 วิชาลมหายใจครรภ์ต้นกำเนิด", id="Gong13_Esoterica_12", cat="☯ DLC บู๊ตึ้ง", story="Xaou_BookProxy_209", sourceStory="BookShop_WuDang_2", cache="ItemCache5" },
    { text="📖 🌊 เส้นลมปราณเก้าหยิน", id="Gong13_Esoterica_8", cat="☯ DLC บู๊ตึ้ง", story="Xaou_BookProxy_210", sourceStory="BookShop_WuDang_2", cache="ItemCache6" },
    { text="📖 🔥 คัมภีร์บู๊ตึ้ง: 为剑", id="Gong13_Esoterica_21", cat="☯ DLC บู๊ตึ้ง", story="Xaou_BookProxy_211", sourceStory="BookShop_WuDang_2", cache="ItemCache7" },
    { text="📖 🔥 คัมภีร์บู๊ตึ้ง: 登霄六步", id="Gong13_Esoterica_27", cat="☯ DLC บู๊ตึ้ง", story="Xaou_BookProxy_212", sourceStory="BookShop_WuDang_2", cache="ItemCache8" },
    { text="📖 🔥 คัมภีร์บู๊ตึ้ง: 虚极剑", id="Gong13_Esoterica_18", cat="☯ DLC บู๊ตึ้ง", story="Xaou_BookProxy_213", sourceStory="BookShop_WuDang_2", cache="ItemCache9" },
    { text="📖 🔥 คัมภีร์บู๊ตึ้ง: 观复诀", id="Gong13_Esoterica_24", cat="☯ DLC บู๊ตึ้ง", story="Xaou_BookProxy_214", sourceStory="BookShop_WuDang_2", cache="ItemCache10" },
    { text="📖 🔥 ปราณแท้หยางบริสุทธิ์", id="Gong13_Esoterica_14", cat="☯ DLC บู๊ตึ้ง", story="Xaou_BookProxy_215", sourceStory="BookShop_WuDang_2", cache="ItemCache11" },
    { text="📖 🔥 รูปแท้หกหยาง", id="Gong13_Esoterica_7", cat="☯ DLC บู๊ตึ้ง", story="Xaou_BookProxy_216", sourceStory="BookShop_WuDang_2", cache="ItemCache12" },
    { text="📖 🔥 วิชามองความบริสุทธิ์", id="Gong13_Esoterica_1", cat="☯ DLC บู๊ตึ้ง", story="Xaou_BookProxy_217", sourceStory="BookShop_WuDang_2", cache="ItemCache13" },
    { text="📖 🔥 วิชาหายใจฟ้าเวหา", id="Gong13_Esoterica_11", cat="☯ DLC บู๊ตึ้ง", story="Xaou_BookProxy_218", sourceStory="BookShop_WuDang_2", cache="ItemCache14" },
    { text="📖 🔥 เคล็ดอัคคีหยาง", id="Gong13_Esoterica_4", cat="☯ DLC บู๊ตึ้ง", story="Xaou_BookProxy_219", sourceStory="BookShop_WuDang_2", cache="ItemCache15" },
    { text="📖 คืนแสงเคล็ด", id="Gong4_Esoterica_3", cat="🌀 ทักษะ/เคล็ดวิชา", story="Xaou_BookProxy_220", sourceStory="BookShop_Skill_1", cache="ItemCache2" },
    { text="📖 ปราณกังแต่กำเนิด", id="FightSkillEsoterica_1", cat="🌀 ทักษะ/เคล็ดวิชา", story="Xaou_BookProxy_221", sourceStory="BookShop_Skill_1", cache="ItemCache3" },
    { text="📖 อัสนีเทพไท่ซวีหยู่ชิง", id="FightSkillEsoterica_Gong4_1", cat="🌀 ทักษะ/เคล็ดวิชา", story="Xaou_BookProxy_222", sourceStory="BookShop_Skill_1", cache="ItemCache4" },
    { text="📖 เคล็ดวิชา: 元始之胎", id="Gong4_Esoterica_7", cat="🌀 ทักษะ/เคล็ดวิชา", story="Xaou_BookProxy_223", sourceStory="BookShop_Skill_1", cache="ItemCache5" },
    { text="📖 แสงเทพแม่เหล็กทำลายล้าง", id="FightSkillEsoterica_4", cat="🌀 ทักษะ/เคล็ดวิชา", story="Xaou_BookProxy_224", sourceStory="BookShop_Skill_1", cache="ItemCache6" },
    { text="📖 ⚙ กระบี่เทพสะท้อนเสียง", id="FightSkillEsoterica_Gong3_1", cat="🌀 ทักษะ/เคล็ดวิชา", story="Xaou_BookProxy_225", sourceStory="BookShop_Skill_1", cache="ItemCache7" },
    { text="📖 ⚙ อัสนีเทพทองเกิง", id="FightSkillEsoterica_3", cat="🌀 ทักษะ/เคล็ดวิชา", story="Xaou_BookProxy_226", sourceStory="BookShop_Skill_1", cache="ItemCache8" },
    { text="📖 ⛰ โล่ปฐพีหนา", id="FightSkillEsoterica_Gong4_2", cat="🌀 ทักษะ/เคล็ดวิชา", story="Xaou_BookProxy_227", sourceStory="BookShop_Skill_1", cache="ItemCache9" },
    { text="📖 🌊 วิชาวารีสวรรค์สลายบาดแผล", id="FightSkillEsoterica_Gong1_1", cat="🌀 ทักษะ/เคล็ดวิชา", story="Xaou_BookProxy_228", sourceStory="BookShop_Skill_1", cache="ItemCache10" },
    { text="📖 🌊 เคล็ดควบคุมปราณไท่เหอ", id="Gong1_Esoterica_2", cat="🌀 ทักษะ/เคล็ดวิชา", story="Xaou_BookProxy_229", sourceStory="BookShop_Skill_1", cache="ItemCache11" },
    { text="📖 🌳 ย้อนวัฏสงสาร", id="FightSkillEsoterica_Gong9_1", cat="🌀 ทักษะ/เคล็ดวิชา", story="Xaou_BookProxy_230", sourceStory="BookShop_Skill_1", cache="ItemCache12" },
    { text="📖 🌳 เคล็ดคืนวสันต์", id="FightSkillEsoterica_Gong4_3", cat="🌀 ทักษะ/เคล็ดวิชา", story="Xaou_BookProxy_231", sourceStory="BookShop_Skill_1", cache="ItemCache13" },
    { text="📖 🌳 เคล็ดวิชา: 天人之体·一阶", id="Gong9_Esoterica_12", cat="🌀 ทักษะ/เคล็ดวิชา", story="Xaou_BookProxy_232", sourceStory="BookShop_Skill_1", cache="ItemCache14" },
    { text="📖 🌳 เคล็ดวิชา: 松影千霞", id="Other_Esoterica_DanXia1", cat="🌀 ทักษะ/เคล็ดวิชา", story="Xaou_BookProxy_233", sourceStory="BookShop_Skill_1", cache="ItemCache15" },
    { text="📖 🌳 เคล็ดวิชา: 生死录", id="Gong9_Esoterica_3", cat="🌀 ทักษะ/เคล็ดวิชา", story="Xaou_BookProxy_234", sourceStory="BookShop_Skill_1", cache="ItemCache16" },
    { text="📖 🌳 เคล็ดวิชา: 轮回之体", id="Gong9_Esoterica_4", cat="🌀 ทักษะ/เคล็ดวิชา", story="Xaou_BookProxy_235", sourceStory="BookShop_Skill_1", cache="ItemCache17" },
    { text="📖 🌳 เคล็ดวิชา: 轮回之心", id="Gong9_Esoterica_5", cat="🌀 ทักษะ/เคล็ดวิชา", story="Xaou_BookProxy_236", sourceStory="BookShop_Skill_1", cache="ItemCache18" },
    { text="📖 🔥 เคล็ดวิชา: 三阳赤心咒", id="Gong10_Esoterica_2", cat="🌀 ทักษะ/เคล็ดวิชา", story="Xaou_BookProxy_237", sourceStory="BookShop_Skill_1", cache="ItemCache19" },
    { text="📖 🔥 เคล็ดวิชา: 御真秘典", id="Gong10_Esoterica_1", cat="🌀 ทักษะ/เคล็ดวิชา", story="Xaou_BookProxy_238", sourceStory="BookShop_Skill_1", cache="ItemCache20" },
    { text="📖 🔥 เคล็ดวิชา: 真火炼身", id="Gong10_Esoterica_4", cat="🌀 ทักษะ/เคล็ดวิชา", story="Xaou_BookProxy_239", sourceStory="BookShop_Skill_1", cache="ItemCache21" },
    { text="📖 🔥 เคล็ดวิชา: 通天神火咒", id="Gong10_Esoterica_9", cat="🌀 ทักษะ/เคล็ดวิชา", story="Xaou_BookProxy_240", sourceStory="BookShop_Skill_2", cache="ItemCache2" },
    { text="📖 🔥 เคล็ดเปลวเพลิง", id="FightSkillEsoterica_2", cat="🌀 ทักษะ/เคล็ดวิชา", story="Xaou_BookProxy_241", sourceStory="BookShop_Skill_2", cache="ItemCache3" },
    { text="📖 🔥 เริ่มตะวันแท้เคล็ด", id="Gong10_Esoterica_3", cat="🌀 ทักษะ/เคล็ดวิชา", story="Xaou_BookProxy_242", sourceStory="BookShop_Skill_2", cache="ItemCache4" },
    { text="📖 🔥 ใจอัคคี", id="Gong10_Esoterica_8", cat="🌀 ทักษะ/เคล็ดวิชา", story="Xaou_BookProxy_243", sourceStory="BookShop_Skill_2", cache="ItemCache5" },
    { text="📖 ควบคุมพฤกษาเคล็ด", id="Magic_PlantGrowUp_1", cat="✨ วิชาเวท", story="Xaou_BookProxy_244", sourceStory="BookShop_Magic_1", cache="ItemCache2" },
    { text="📖 ชิงใจมนต์", id="Magic_AbsorbGong_8_1", cat="✨ วิชาเวท", story="Xaou_BookProxy_245", sourceStory="BookShop_Magic_1", cache="ItemCache3" },
    { text="📖 ตรวจฮวงจุ้ย", id="Magic_FengshuiItemOpen", cat="✨ วิชาเวท", story="Xaou_BookProxy_246", sourceStory="BookShop_Magic_1", cache="ItemCache4" },
    { text="📖 มนต์ใจประสาน", id="Magic_KongZhi1", cat="✨ วิชาเวท", story="Xaou_BookProxy_247", sourceStory="BookShop_Magic_1", cache="ItemCache5" },
    { text="📖 มหาวิชาค้นวิญญาณ", id="SeachSoul", cat="✨ วิชาเวท", story="Xaou_BookProxy_248", sourceStory="BookShop_Magic_1", cache="ItemCache6" },
    { text="📖 ระบำมารสวรรค์", id="Magic_KongZhi3", cat="✨ วิชาเวท", story="Xaou_BookProxy_249", sourceStory="BookShop_Magic_1", cache="ItemCache7" },
    { text="📖 วิชาควบคุมวิญญาณ", id="Magic_MakePuppet", cat="✨ วิชาเวท", story="Xaou_BookProxy_250", sourceStory="BookShop_Magic_1", cache="ItemCache8" },
    { text="📖 วิชาประทานวิญญาณ", id="Magic_BuidPuppet", cat="✨ วิชาเวท", story="Xaou_BookProxy_251", sourceStory="BookShop_Magic_1", cache="ItemCache9" },
    { text="📖 วิชาฝนทิพย์", id="Magic_GanLingShu", cat="✨ วิชาเวท", story="Xaou_BookProxy_252", sourceStory="BookShop_Magic_1", cache="ItemCache10" },
    { text="📖 วิชาหลอมจิต", id="Magic_SoulCrystalLingPowerUp", cat="✨ วิชาเวท", story="Xaou_BookProxy_253", sourceStory="BookShop_Magic_1", cache="ItemCache11" },
    { text="📖 วิชาหลอมอสูร", id="Magic_SoulCrystalYouPowerUp", cat="✨ วิชาเวท", story="Xaou_BookProxy_254", sourceStory="BookShop_Magic_1", cache="ItemCache12" },
    { text="📖 วิชาหลอมเต๋า", id="Magic_JieHuiDaoPowerUp", cat="✨ วิชาเวท", story="Xaou_BookProxy_255", sourceStory="BookShop_Magic_1", cache="ItemCache13" },
    { text="📖 วิชาเกิดใหม่เสวียนพิน", id="Magic_RebornSelf", cat="✨ วิชาเวท", story="Xaou_BookProxy_256", sourceStory="BookShop_Magic_1", cache="ItemCache14" },
    { text="📖 วิชาเข้าสมาธิ", id="Magic_ClosedDoor_1", cat="✨ วิชาเวท", story="Xaou_BookProxy_257", sourceStory="BookShop_Magic_1", cache="ItemCache15" },
    { text="📖 วิชาเวท: 他化自在大法", id="Magic_AbsorbGong_5_1", cat="✨ วิชาเวท", story="Xaou_BookProxy_258", sourceStory="BookShop_Magic_1", cache="ItemCache16" },
    { text="📖 วิชาเวท: 伐毛洗髓之术", id="Magic_Healing_Physique_1", cat="✨ วิชาเวท", story="Xaou_BookProxy_259", sourceStory="BookShop_Magic_1", cache="ItemCache17" },
    { text="📖 วิชาเวท: 六壬神算", id="Magic_LiuRenShensuan", cat="✨ วิชาเวท", story="Xaou_BookProxy_260", sourceStory="BookShop_Magic_1", cache="ItemCache18" },
    { text="📖 วิชาเวท: 再造形神之术", id="Magic_Healing_Charisma_1", cat="✨ วิชาเวท", story="Xaou_BookProxy_261", sourceStory="BookShop_Magic_1", cache="ItemCache19" },
    { text="📖 วิชาเวท: 再造术", id="Magic_BuildBody_1", cat="✨ วิชาเวท", story="Xaou_BookProxy_262", sourceStory="BookShop_Magic_1", cache="ItemCache20" },
    { text="📖 วิชาเวท: 冥灵真法", id="Magic_AbsorbLing_Live_1", cat="✨ วิชาเวท", story="Xaou_BookProxy_263", sourceStory="BookShop_Magic_1", cache="ItemCache21" },
    { text="📖 วิชาเวท: 化伤术", id="Magic_Healing_Damage_1", cat="✨ วิชาเวท", story="Xaou_BookProxy_264", sourceStory="BookShop_Magic_2", cache="ItemCache2" },
    { text="📖 วิชาเวท: 吸星掌", id="Magic_AbsorbLing_Item_1", cat="✨ วิชาเวท", story="Xaou_BookProxy_265", sourceStory="BookShop_Magic_2", cache="ItemCache3" },
    { text="📖 วิชาเวท: 周天神算", id="Magic_Prophesy_1", cat="✨ วิชาเวท", story="Xaou_BookProxy_266", sourceStory="BookShop_Magic_2", cache="ItemCache4" },
    { text="📖 วิชาเวท: 大衍神算", id="Magic_Prophesy_MapStory_1", cat="✨ วิชาเวท", story="Xaou_BookProxy_267", sourceStory="BookShop_Magic_2", cache="ItemCache5" },
    { text="📖 วิชาเวท: 天妖化血术", id="Magic_AbsorbLing_Body_1", cat="✨ วิชาเวท", story="Xaou_BookProxy_268", sourceStory="BookShop_Magic_2", cache="ItemCache6" },
    { text="📖 วิชาเวท: 天心正法", id="Magic_AbsorbGong_9_1", cat="✨ วิชาเวท", story="Xaou_BookProxy_269", sourceStory="BookShop_Magic_2", cache="ItemCache7" },
    { text="📖 วิชาเวท: 天魔化身术", id="Magic_AbsorbGong_4_1", cat="✨ วิชาเวท", story="Xaou_BookProxy_270", sourceStory="BookShop_Magic_2", cache="ItemCache8" },
    { text="📖 วิชาเวท: 天魔解体大法", id="Magic_AbsorbGong_9_2", cat="✨ วิชาเวท", story="Xaou_BookProxy_271", sourceStory="BookShop_Magic_2", cache="ItemCache9" },
    { text="📖 วิชาเวท: 尘暴术", id="Magic_PrayForDustStorm", cat="✨ วิชาเวท", story="Xaou_BookProxy_272", sourceStory="BookShop_Magic_2", cache="ItemCache10" },
    { text="📖 วิชาเวท: 开天眼之术", id="Magic_Healing_Perception_1", cat="✨ วิชาเวท", story="Xaou_BookProxy_273", sourceStory="BookShop_Magic_2", cache="ItemCache11" },
    { text="📖 วิชาเวท: 慧剑斩念", id="Magic_AbsorbGong_10_1", cat="✨ วิชาเวท", story="Xaou_BookProxy_274", sourceStory="BookShop_Magic_2", cache="ItemCache12" },
    { text="📖 วิชาเวท: 托体同山诀", id="Magic_AbsorbLing_Thing_1", cat="✨ วิชาเวท", story="Xaou_BookProxy_275", sourceStory="BookShop_Magic_2", cache="ItemCache13" },
    { text="📖 วิชาเวท: 摄神御鬼大法", id="Magic_AbsorbGong_3_1", cat="✨ วิชาเวท", story="Xaou_BookProxy_276", sourceStory="BookShop_Magic_2", cache="ItemCache14" },
    { text="📖 วิชาเวท: 暴雨术", id="Magic_PrayForRainstorm", cat="✨ วิชาเวท", story="Xaou_BookProxy_277", sourceStory="BookShop_Magic_2", cache="ItemCache15" },
    { text="📖 วิชาเวท: 毒瘴术", id="Magic_PrayForMiasma", cat="✨ วิชาเวท", story="Xaou_BookProxy_278", sourceStory="BookShop_Magic_2", cache="ItemCache16" },
    { text="📖 วิชาเวท: 求雨术", id="Magic_PrayForRain_1", cat="✨ วิชาเวท", story="Xaou_BookProxy_279", sourceStory="BookShop_Magic_2", cache="ItemCache17" },
    { text="📖 วิชาเวท: 炼制灵晶之术", id="Magic_LingCrystalMake_1", cat="✨ วิชาเวท", story="Xaou_BookProxy_280", sourceStory="BookShop_Magic_2", cache="ItemCache18" },
    { text="📖 วิชาเวท: 炼制灵石之术", id="Magic_LingStoneMake_1", cat="✨ วิชาเวท", story="Xaou_BookProxy_281", sourceStory="BookShop_Magic_2", cache="ItemCache19" },
    { text="📖 วิชาเวท: 焚风术", id="Magic_PrayForFohn", cat="✨ วิชาเวท", story="Xaou_BookProxy_282", sourceStory="BookShop_Magic_2", cache="ItemCache20" },
    { text="📖 วิชาเวท: 献祭", id="Magic_AbsorbGong_7_1", cat="✨ วิชาเวท", story="Xaou_BookProxy_283", sourceStory="BookShop_Magic_2", cache="ItemCache21" },
    { text="📖 วิชาเวท: 祈天经", id="Magic_PrayForWeather", cat="✨ วิชาเวท", story="Xaou_BookProxy_284", sourceStory="BookShop_Magic_3", cache="ItemCache2" },
    { text="📖 วิชาเวท: 醍醐灌顶之术", id="Magic_Healing_Intelligence_1", cat="✨ วิชาเวท", story="Xaou_BookProxy_285", sourceStory="BookShop_Magic_3", cache="ItemCache3" },
    { text="📖 วิชาเวท: 阳神夺舍", id="Magic_RobBodyHigh_1", cat="✨ วิชาเวท", story="Xaou_BookProxy_286", sourceStory="BookShop_Magic_3", cache="ItemCache4" },
    { text="📖 วิชาเวท: 阴神夺舍", id="Magic_RobBodyLow_1", cat="✨ วิชาเวท", story="Xaou_BookProxy_287", sourceStory="BookShop_Magic_3", cache="ItemCache5" },
    { text="📖 วิชาเวท: 雷暴术", id="Magic_PrayForLightningStorm", cat="✨ วิชาเวท", story="Xaou_BookProxy_288", sourceStory="BookShop_Magic_3", cache="ItemCache6" },
    { text="📖 วิชาเวท: 风月幻境", id="Magic_AbsorbGong_2_1", cat="✨ วิชาเวท", story="Xaou_BookProxy_289", sourceStory="BookShop_Magic_3", cache="ItemCache7" },
    { text="📖 วิชาเวท: 驱云诀", id="Magic_PrayForSun_1", cat="✨ วิชาเวท", story="Xaou_BookProxy_290", sourceStory="BookShop_Magic_3", cache="ItemCache8" },
    { text="📖 วิชาเวท: 魂体寄生", id="Magic_AbsorbGong_6_1", cat="✨ วิชาเวท", story="Xaou_BookProxy_291", sourceStory="BookShop_Magic_3", cache="ItemCache9" },
    { text="📖 วิชาเวท: 鼎炉吸真术", id="Magic_AbsorbGong_1_1", cat="✨ วิชาเวท", story="Xaou_BookProxy_292", sourceStory="BookShop_Magic_3", cache="ItemCache10" },
    { text="📖 วิชาแยกจิต", id="Magic_FenShenZhiShu", cat="✨ วิชาเวท", story="Xaou_BookProxy_293", sourceStory="BookShop_Magic_3", cache="ItemCache11" },
    { text="📖 วิชาแยกจิต", id="Magic_FenShenZhiShu_1", cat="✨ วิชาเวท", story="Xaou_BookProxy_294", sourceStory="BookShop_Magic_3", cache="ItemCache12" },
    { text="📖 ห้าตราประทับเทพ", id="Magic_KongZhi4", cat="✨ วิชาเวท", story="Xaou_BookProxy_295", sourceStory="BookShop_Magic_3", cache="ItemCache13" },
    { text="📖 เคล็ดกลั่นอำพัน", id="Magic_MakeSoulCrystal", cat="✨ วิชาเวท", story="Xaou_BookProxy_296", sourceStory="BookShop_Magic_3", cache="ItemCache14" },
    { text="📖 เคล็ดประทับใจ", id="Magic_KongZhi2", cat="✨ วิชาเวท", story="Xaou_BookProxy_297", sourceStory="BookShop_Magic_3", cache="ItemCache15" },
    { text="📖 เคล็ดลมหายใจวิญญาณ", id="Magic_AbsorbLing_Aoe_1", cat="✨ วิชาเวท", story="Xaou_BookProxy_298", sourceStory="BookShop_Magic_3", cache="ItemCache16" },
    { text="📖 ⛰ วิชาพิสดารหยวนคุน", id="Magic_BuildMine", cat="✨ วิชาเวท", story="Xaou_BookProxy_299", sourceStory="BookShop_Magic_3", cache="ItemCache17" },
    { text="📖 ⛰ วิชาสร้างแผ่นดิน", id="Magic_BuildMine_ZaoLu", cat="✨ วิชาเวท", story="Xaou_BookProxy_300", sourceStory="BookShop_Magic_3", cache="ItemCache18" },
    { text="📖 🌊 วิชาเปิดทะเลสาบ", id="Magic_BuildMine_KaiHu", cat="✨ วิชาเวท", story="Xaou_BookProxy_301", sourceStory="BookShop_Magic_3", cache="ItemCache19" },
    { text="📖 วิชาเวทพิเศษ: 元灵补天诀", id="Magic_YuanLing", cat="✨ วิชาเวทพิเศษ", story="Xaou_BookProxy_302", sourceStory="BookShop_Magic2_1", cache="ItemCache2" },
    { text="📖 วิชาเวทพิเศษ: 命火筑灵", id="Magic_WanWuTongLing2", cat="✨ วิชาเวทพิเศษ", story="Xaou_BookProxy_303", sourceStory="BookShop_Magic2_1", cache="ItemCache3" },
    { text="📖 วิชาเวทพิเศษ: 封灵术", id="Magic_MakeHorse_1", cat="✨ วิชาเวทพิเศษ", story="Xaou_BookProxy_304", sourceStory="BookShop_Magic2_1", cache="ItemCache4" },
    { text="📖 วิชาเวทพิเศษ: 玄魂造命", id="Magic_WanWuTongLing1", cat="✨ วิชาเวทพิเศษ", story="Xaou_BookProxy_305", sourceStory="BookShop_Magic2_1", cache="ItemCache5" },
    { text="📖 วิชาเวทพิเศษ: 造化塑体", id="Magic_ZaoHuaSuTi", cat="✨ วิชาเวทพิเศษ", story="Xaou_BookProxy_306", sourceStory="BookShop_Magic2_1", cache="ItemCache6" },
    { text="📖 กลางต้นกำเนิดภูเขาบริสุทธิ์ขั้วค่ายกลแผนภาพ", id="Esoterica_ZhenFa_4", cat="🧿 ค่ายกล", story="Xaou_BookProxy_307", sourceStory="BookShop_Zhen_1", cache="ItemCache2" },
    { text="📖 ค่ายกลเทพเหอหลัวก่อนกำเนิด：คำอธิบายแท้จักรพรรดิมาร", id="Esoterica_ZhenFa_15", cat="🧿 ค่ายกล", story="Xaou_BookProxy_308", sourceStory="BookShop_Zhen_1", cache="ItemCache3" },
    { text="📖 ค่ายกลเทพเหอหลัวก่อนกำเนิด：บทดินคุน", id="Esoterica_ZhenFa_8", cat="🧿 ค่ายกล", story="Xaou_BookProxy_309", sourceStory="BookShop_Zhen_1", cache="ItemCache4" },
    { text="📖 ค่ายกลเทพเหอหลัวก่อนกำเนิด：บทบึงตุ้ย", id="Esoterica_ZhenFa_14", cat="🧿 ค่ายกล", story="Xaou_BookProxy_310", sourceStory="BookShop_Zhen_1", cache="ItemCache5" },
    { text="📖 ค่ายกลเทพเหอหลัวก่อนกำเนิด：บทฟ้าเฉียน", id="Esoterica_ZhenFa_7", cat="🧿 ค่ายกล", story="Xaou_BookProxy_311", sourceStory="BookShop_Zhen_1", cache="ItemCache6" },
    { text="📖 ค่ายกลเทพเหอหลัวก่อนกำเนิด：บทภาพรวม", id="Esoterica_ZhenFa_6", cat="🧿 ค่ายกล", story="Xaou_BookProxy_312", sourceStory="BookShop_Zhen_1", cache="ItemCache7" },
    { text="📖 ค่ายกลเทพเหอหลัวก่อนกำเนิด：บทภูเขาเกิ้น", id="Esoterica_ZhenFa_13", cat="🧿 ค่ายกล", story="Xaou_BookProxy_313", sourceStory="BookShop_Zhen_1", cache="ItemCache8" },
    { text="📖 ค่ายกลเทพเหอหลัวก่อนกำเนิด：บทวายุซวิ่น", id="Esoterica_ZhenFa_10", cat="🧿 ค่ายกล", story="Xaou_BookProxy_314", sourceStory="BookShop_Zhen_1", cache="ItemCache9" },
    { text="📖 ค่ายกลเทพเหอหลัวก่อนกำเนิด：บทวารีข่าน", id="Esoterica_ZhenFa_11", cat="🧿 ค่ายกล", story="Xaou_BookProxy_315", sourceStory="BookShop_Zhen_1", cache="ItemCache10" },
    { text="📖 ค่ายกลเทพเหอหลัวก่อนกำเนิด：บทอัคคีหลี", id="Esoterica_ZhenFa_12", cat="🧿 ค่ายกล", story="Xaou_BookProxy_316", sourceStory="BookShop_Zhen_1", cache="ItemCache11" },
    { text="📖 ค่ายกลเทพเหอหลัวก่อนกำเนิด：บทอัสนีเจิ้น", id="Esoterica_ZhenFa_9", cat="🧿 ค่ายกล", story="Xaou_BookProxy_317", sourceStory="BookShop_Zhen_1", cache="ItemCache12" },
    { text="📖 ค่ายกลแปลงเต๋าสวรรค์：วิถีจักรวาล", id="Esoterica_ZhenFa_18", cat="🧿 ค่ายกล", story="Xaou_BookProxy_318", sourceStory="BookShop_Zhen_1", cache="ItemCache13" },
    { text="📖 ค่ายกลแปลงเต๋าสวรรค์：วิถีสุริยันจันทรา", id="Esoterica_ZhenFa_16", cat="🧿 ค่ายกล", story="Xaou_BookProxy_319", sourceStory="BookShop_Zhen_1", cache="ItemCache14" },
    { text="📖 ค่ายกลแปลงเต๋าสวรรค์：วิถีหยินหยาง", id="Esoterica_ZhenFa_17", cat="🧿 ค่ายกล", story="Xaou_BookProxy_320", sourceStory="BookShop_Zhen_1", cache="ItemCache15" },
    { text="📖 ค่ายกลแปลงเต๋าสวรรค์：วิถีเกิดดับ", id="Esoterica_ZhenFa_20", cat="🧿 ค่ายกล", story="Xaou_BookProxy_321", sourceStory="BookShop_Zhen_1", cache="ItemCache16" },
    { text="📖 ค่ายกลแปลงเต๋าสวรรค์：วิถีเริ่มและจบ", id="Esoterica_ZhenFa_19", cat="🧿 ค่ายกล", story="Xaou_BookProxy_322", sourceStory="BookShop_Zhen_1", cache="ItemCache17" },
    { text="📖 ตำราค่ายกล: 九御赋龙形阵", id="Esoterica_ZhenFa_Suit5", cat="🧿 ค่ายกล", story="Xaou_BookProxy_323", sourceStory="BookShop_Zhen_1", cache="ItemCache18" },
    { text="📖 ตำราค่ายกล: 五峰镇归墟", id="Esoterica_ZhenFa_Suit11", cat="🧿 ค่ายกล", story="Xaou_BookProxy_324", sourceStory="BookShop_Zhen_1", cache="ItemCache19" },
    { text="📖 ตำราค่ายกล: 先天甲乙木神阵", id="Esoterica_ZhenFa_Suit10", cat="🧿 ค่ายกล", story="Xaou_BookProxy_325", sourceStory="BookShop_Zhen_1", cache="ItemCache20" },
    { text="📖 ตำราค่ายกล: 八门玄金天劫剑阵", id="Esoterica_ZhenFa_Suit9", cat="🧿 ค่ายกล", story="Xaou_BookProxy_326", sourceStory="BookShop_Zhen_1", cache="ItemCache21" },
    { text="📖 ตำราค่ายกล: 北斗真武戮魔大阵", id="Esoterica_ZhenFa_Suit2", cat="🧿 ค่ายกล", story="Xaou_BookProxy_327", sourceStory="BookShop_Zhen_2", cache="ItemCache2" },
    { text="📖 ตำราค่ายกล: 天地五方不灭阵", id="Esoterica_ZhenFa_Suit3", cat="🧿 ค่ายกล", story="Xaou_BookProxy_328", sourceStory="BookShop_Zhen_2", cache="ItemCache3" },
    { text="📖 ตำราค่ายกล: 天道化阵：造化之道", id="Esoterica_ZhenFa_21", cat="🧿 ค่ายกล", story="Xaou_BookProxy_329", sourceStory="BookShop_Zhen_2", cache="ItemCache4" },
    { text="📖 ตำราค่ายกล: 法天效地归元阵法秘录", id="Esoterica_ZhenFa_5", cat="🧿 ค่ายกล", story="Xaou_BookProxy_330", sourceStory="BookShop_Zhen_2", cache="ItemCache5" },
    { text="📖 ตำราค่ายกล: 真凰羽剑阵", id="Esoterica_ZhenFa_Suit6", cat="🧿 ค่ายกล", story="Xaou_BookProxy_331", sourceStory="BookShop_Zhen_2", cache="ItemCache6" },
    { text="📖 ตำราค่ายกล: 诛仙剑阵", id="Esoterica_ZhenFa_Suit1", cat="🧿 ค่ายกล", story="Xaou_BookProxy_332", sourceStory="BookShop_Zhen_2", cache="ItemCache7" },
    { text="📖 ตำราค่ายกล: 诸天六御行法仪轨", id="Esoterica_ZhenFa_Suit4", cat="🧿 ค่ายกล", story="Xaou_BookProxy_333", sourceStory="BookShop_Zhen_2", cache="ItemCache8" },
    { text="📖 ตำราค่ายกล: 鸿蒙之阵：万灵生发", id="Esoterica_ZhenFa_24", cat="🧿 ค่ายกล", story="Xaou_BookProxy_334", sourceStory="BookShop_Zhen_2", cache="ItemCache9" },
    { text="📖 ตำราค่ายกล: 鸿蒙之阵：万物陨灭", id="Esoterica_ZhenFa_27", cat="🧿 ค่ายกล", story="Xaou_BookProxy_335", sourceStory="BookShop_Zhen_2", cache="ItemCache10" },
    { text="📖 ตำราค่ายกล: 鸿蒙之阵：天地开辟", id="Esoterica_ZhenFa_22", cat="🧿 ค่ายกล", story="Xaou_BookProxy_336", sourceStory="BookShop_Zhen_2", cache="ItemCache11" },
    { text="📖 ตำราค่ายกล: 鸿蒙之阵：天地归寂", id="Esoterica_ZhenFa_25", cat="🧿 ค่ายกล", story="Xaou_BookProxy_337", sourceStory="BookShop_Zhen_2", cache="ItemCache12" },
    { text="📖 ตำราค่ายกล: 鸿蒙之阵：时空尽衰", id="Esoterica_ZhenFa_26", cat="🧿 ค่ายกล", story="Xaou_BookProxy_338", sourceStory="BookShop_Zhen_2", cache="ItemCache13" },
    { text="📖 ตำราค่ายกล: 鸿蒙之阵：时空衍生", id="Esoterica_ZhenFa_23", cat="🧿 ค่ายกล", story="Xaou_BookProxy_339", sourceStory="BookShop_Zhen_2", cache="ItemCache14" },
    { text="📖 ตำราค่ายกลหมื่นอสูรคืนวิญญาณ", id="Esoterica_ZhenFa_3", cat="🧿 ค่ายกล", story="Xaou_BookProxy_340", sourceStory="BookShop_Zhen_2", cache="ItemCache15" },
    { text="📖 บันทึกค่ายกลไท้อี้", id="Esoterica_ZhenFa_1", cat="🧿 ค่ายกล", story="Xaou_BookProxy_341", sourceStory="BookShop_Zhen_2", cache="ItemCache16" },
    { text="📖 สามหยินสามสุดยอดค่ายกล", id="Esoterica_ZhenFa_Suit8", cat="🧿 ค่ายกล", story="Xaou_BookProxy_342", sourceStory="BookShop_Zhen_2", cache="ItemCache17" },
    { text="📖 หยินหยางสองธาตุเทพค่ายกล", id="Esoterica_ZhenFa_Suit7", cat="🧿 ค่ายกล", story="Xaou_BookProxy_343", sourceStory="BookShop_Zhen_2", cache="ItemCache18" },
    { text="📖 แผนค่ายกลสี่พิทักษ์ไท้อี้", id="Esoterica_ZhenFa_2", cat="🧿 ค่ายกล", story="Xaou_BookProxy_344", sourceStory="BookShop_Zhen_2", cache="ItemCache19" },
    { text="📖 ศาสตราเทพเต๋าสวรรค์", id="God2_Fabao", cat="🗡 อาวุธวิเศษ", story="Xaou_BookProxy_345", sourceStory="BookShop_Fabao_1", cache="ItemCache2" },
    { text="📖 ⚙ ขั้วกระบี่·หนึ่ง", id="Gong3_Esoterica_9", cat="🗡 อาวุธวิเศษ", story="Xaou_BookProxy_346", sourceStory="BookShop_Fabao_1", cache="ItemCache3" },
    { text="📖 ⚙ ควบคุมกระบี่วิชา", id="Gong3_Esoterica_4", cat="🗡 อาวุธวิเศษ", story="Xaou_BookProxy_347", sourceStory="BookShop_Fabao_1", cache="ItemCache4" },
    { text="📖 ⚙ ตำราลับตงหัว-กระบี่จื่อเวย", id="Other_Esoterica_DengXian1", cat="🗡 อาวุธวิเศษ", story="Xaou_BookProxy_348", sourceStory="BookShop_Fabao_1", cache="ItemCache5" },
    { text="📖 ⚙ ตำราอาวุธวิเศษ: 击字诀", id="Gong3_Esoterica_11", cat="🗡 อาวุธวิเศษ", story="Xaou_BookProxy_349", sourceStory="BookShop_Fabao_1", cache="ItemCache6" },
    { text="📖 ⚙ ตำราอาวุธวิเศษ: 分字诀", id="Gong3_Esoterica_19", cat="🗡 อาวุธวิเศษ", story="Xaou_BookProxy_350", sourceStory="BookShop_Fabao_1", cache="ItemCache7" },
    { text="📖 ⚙ ตำราอาวุธวิเศษ: 刺字诀", id="Gong3_Esoterica_12", cat="🗡 อาวุธวิเศษ", story="Xaou_BookProxy_351", sourceStory="BookShop_Fabao_1", cache="ItemCache8" },
    { text="📖 ⚙ ตำราอาวุธวิเศษ: 剑心通明", id="Gong3_Esoterica_5", cat="🗡 อาวุธวิเศษ", story="Xaou_BookProxy_352", sourceStory="BookShop_Fabao_1", cache="ItemCache9" },
    { text="📖 ⚙ ตำราอาวุธวิเศษ: 劈字诀", id="Gong3_Esoterica_16", cat="🗡 อาวุธวิเศษ", story="Xaou_BookProxy_353", sourceStory="BookShop_Fabao_1", cache="ItemCache10" },
    { text="📖 ⚙ ตำราอาวุธวิเศษ: 化字诀", id="Gong3_Esoterica_18", cat="🗡 อาวุธวิเศษ", story="Xaou_BookProxy_354", sourceStory="BookShop_Fabao_1", cache="ItemCache11" },
    { text="📖 ⚙ ตำราอาวุธวิเศษ: 天权诀", id="Gong8_Esoterica_6", cat="🗡 อาวุธวิเศษ", story="Xaou_BookProxy_355", sourceStory="BookShop_Fabao_1", cache="ItemCache12" },
    { text="📖 ⚙ ตำราอาวุธวิเศษ: 天枢诀", id="Gong8_Esoterica_3", cat="🗡 อาวุธวิเศษ", story="Xaou_BookProxy_356", sourceStory="BookShop_Fabao_1", cache="ItemCache13" },
    { text="📖 ⚙ ตำราอาวุธวิเศษ: 天玑诀", id="Gong8_Esoterica_5", cat="🗡 อาวุธวิเศษ", story="Xaou_BookProxy_357", sourceStory="BookShop_Fabao_1", cache="ItemCache14" },
    { text="📖 ⚙ ตำราอาวุธวิเศษ: 天璇诀", id="Gong8_Esoterica_4", cat="🗡 อาวุธวิเศษ", story="Xaou_BookProxy_358", sourceStory="BookShop_Fabao_1", cache="ItemCache15" },
    { text="📖 ⚙ ตำราอาวุธวิเศษ: 崩字诀", id="Gong3_Esoterica_14", cat="🗡 อาวุธวิเศษ", story="Xaou_BookProxy_359", sourceStory="BookShop_Fabao_1", cache="ItemCache16" },
    { text="📖 ⚙ ตำราอาวุธวิเศษ: 开阳诀", id="Gong8_Esoterica_8", cat="🗡 อาวุธวิเศษ", story="Xaou_BookProxy_360", sourceStory="BookShop_Fabao_1", cache="ItemCache17" },
    { text="📖 ⚙ ตำราอาวุธวิเศษ: 御字诀", id="Gong3_Esoterica_17", cat="🗡 อาวุธวิเศษ", story="Xaou_BookProxy_361", sourceStory="BookShop_Fabao_1", cache="ItemCache18" },
    { text="📖 ⚙ ตำราอาวุธวิเศษ: 心剑交感", id="Gong3_Esoterica_6", cat="🗡 อาวุธวิเศษ", story="Xaou_BookProxy_362", sourceStory="BookShop_Fabao_1", cache="ItemCache19" },
    { text="📖 ⚙ ตำราอาวุธวิเศษ: 我剑·一", id="Gong3_Esoterica_10", cat="🗡 อาวุธวิเศษ", story="Xaou_BookProxy_363", sourceStory="BookShop_Fabao_1", cache="ItemCache20" },
    { text="📖 ⚙ ตำราอาวุธวิเศษ: 摇光诀", id="Gong8_Esoterica_9", cat="🗡 อาวุธวิเศษ", story="Xaou_BookProxy_364", sourceStory="BookShop_Fabao_1", cache="ItemCache21" },
    { text="📖 ⚙ ตำราอาวุธวิเศษ: 杀意", id="Gong3_Esoterica_1", cat="🗡 อาวุธวิเศษ", story="Xaou_BookProxy_365", sourceStory="BookShop_Fabao_2", cache="ItemCache2" },
    { text="📖 ⚙ ตำราอาวุธวิเศษ: 洗字诀", id="Gong3_Esoterica_13", cat="🗡 อาวุธวิเศษ", story="Xaou_BookProxy_366", sourceStory="BookShop_Fabao_2", cache="ItemCache3" },
    { text="📖 ⚙ ตำราอาวุธวิเศษ: 点字诀", id="Gong3_Esoterica_15", cat="🗡 อาวุธวิเศษ", story="Xaou_BookProxy_367", sourceStory="BookShop_Fabao_2", cache="ItemCache4" },
    { text="📖 ⚙ ตำราอาวุธวิเศษ: 玉衡诀", id="Gong8_Esoterica_7", cat="🗡 อาวุธวิเศษ", story="Xaou_BookProxy_368", sourceStory="BookShop_Fabao_2", cache="ItemCache5" },
    { text="📖 ⚙ ตำราอาวุธวิเศษ: 真武录", id="Gong8_Esoterica_1", cat="🗡 อาวุธวิเศษ", story="Xaou_BookProxy_369", sourceStory="BookShop_Fabao_2", cache="ItemCache6" },
    { text="📖 ⚙ ตำราอาวุธวิเศษ: 神合剑", id="Gong3_Esoterica_8", cat="🗡 อาวุธวิเศษ", story="Xaou_BookProxy_370", sourceStory="BookShop_Fabao_2", cache="ItemCache7" },
    { text="📖 ⚙ ท่าสุดยอดดาวเหนือ-เจ็ดดาราเคล็ด", id="Gong8_Esoterica_10", cat="🗡 อาวุธวิเศษ", story="Xaou_BookProxy_371", sourceStory="BookShop_Fabao_2", cache="ItemCache8" },
    { text="📖 ⚙ มารไหลจิตกระบี่", id="Gong3_Esoterica_3", cat="🗡 อาวุธวิเศษ", story="Xaou_BookProxy_372", sourceStory="BookShop_Fabao_2", cache="ItemCache9" },
    { text="📖 ⚙ เทพควบคุมกระบี่", id="Gong3_Esoterica_7", cat="🗡 อาวุธวิเศษ", story="Xaou_BookProxy_373", sourceStory="BookShop_Fabao_2", cache="ItemCache10" },
    { text="📖 ⛰ ตำราอาวุธวิเศษ: 坏灭诀", id="Gong11_Esoterica_14", cat="🗡 อาวุธวิเศษ", story="Xaou_BookProxy_374", sourceStory="BookShop_Fabao_2", cache="ItemCache11" },
    { text="📖 ⛰ ตำราอาวุธวิเศษ: 幽剑", id="Gong11_Esoterica_10", cat="🗡 อาวุธวิเศษ", story="Xaou_BookProxy_375", sourceStory="BookShop_Fabao_2", cache="ItemCache12" },
    { text="📖 ⛰ ตำราอาวุธวิเศษ: 渊狱诀", id="Gong11_Esoterica_13", cat="🗡 อาวุธวิเศษ", story="Xaou_BookProxy_376", sourceStory="BookShop_Fabao_2", cache="ItemCache13" },
    { text="📖 ⛰ ตำราอาวุธวิเศษ: 瞬霎诀", id="Gong11_Esoterica_11", cat="🗡 อาวุธวิเศษ", story="Xaou_BookProxy_377", sourceStory="BookShop_Fabao_2", cache="ItemCache14" },
    { text="📖 ⛰ ตำราอาวุธวิเศษ: 辟邪真法", id="Gong11_Esoterica_2", cat="🗡 อาวุธวิเศษ", story="Xaou_BookProxy_378", sourceStory="BookShop_Fabao_2", cache="ItemCache15" },
    { text="📖 ⛰ ไท่หยินเคล็ด", id="Gong11_Esoterica_12", cat="🗡 อาวุธวิเศษ", story="Xaou_BookProxy_379", sourceStory="BookShop_Fabao_2", cache="ItemCache16" },
    { text="📖 🌊 จิตกระบี่ธารเชี่ยว", id="Other_Esoterica_LongHu1", cat="🗡 อาวุธวิเศษ", story="Xaou_BookProxy_380", sourceStory="BookShop_Fabao_2", cache="ItemCache17" },
    { text="📖 🌊 เคล็ดขี่วายุ", id="Gong1_Esoterica_3", cat="🗡 อาวุธวิเศษ", story="Xaou_BookProxy_381", sourceStory="BookShop_Fabao_2", cache="ItemCache18" },
    { text="📖 🌳 ตำราอาวุธวิเศษ: 合物志", id="Gong9_Esoterica_8", cat="🗡 อาวุธวิเศษ", story="Xaou_BookProxy_382", sourceStory="BookShop_Fabao_2", cache="ItemCache19" },
    { text="📖 🔥 ตำราอาวุธวิเศษ: 七情剑", id="Gong7_Esoterica_12", cat="🗡 อาวุธวิเศษ", story="Xaou_BookProxy_383", sourceStory="BookShop_Fabao_2", cache="ItemCache20" },
    { text="📖 🔥 ตำราอาวุธวิเศษ: 坐忘论", id="Gong7_Esoterica_7", cat="🗡 อาวุธวิเศษ", story="Xaou_BookProxy_384", sourceStory="BookShop_Fabao_2", cache="ItemCache21" },
    { text="📖 🔥 ตำราอาวุธวิเศษ: 斩道见我", id="Gong7_Esoterica_10", cat="🗡 อาวุธวิเศษ", story="Xaou_BookProxy_385", sourceStory="BookShop_Fabao_3", cache="ItemCache2" },
    { text="📖 🔥 ตำราอาวุธวิเศษ: 极情剑", id="Gong7_Esoterica_13", cat="🗡 อาวุธวิเศษ", story="Xaou_BookProxy_386", sourceStory="BookShop_Fabao_3", cache="ItemCache3" },
    { text="📖 🔥 ใจกระบี่", id="Gong7_Esoterica_11", cat="🗡 อาวุธวิเศษ", story="Xaou_BookProxy_387", sourceStory="BookShop_Fabao_3", cache="ItemCache4" },
    { text="📖 ตำรากระบี่สังหารเซียน：ฉบับขาดสอง", id="Esoterica_MiBao_2", cat="💎 สมบัติลับ", story="Xaou_BookProxy_388", sourceStory="BookShop_MiBao_1", cache="ItemCache2" },
    { text="📖 ตำรากระบี่สังหารเซียน：ฉบับขาดสาม", id="Esoterica_MiBao_3", cat="💎 สมบัติลับ", story="Xaou_BookProxy_389", sourceStory="BookShop_MiBao_1", cache="ItemCache3" },
    { text="📖 ตำรากระบี่สังหารเซียน：ฉบับขาดสี่", id="Esoterica_MiBao_4", cat="💎 สมบัติลับ", story="Xaou_BookProxy_390", sourceStory="BookShop_MiBao_1", cache="ItemCache4" },
    { text="📖 ตำรากระบี่สังหารเซียน：ฉบับขาดหนึ่ง", id="Esoterica_MiBao_1", cat="💎 สมบัติลับ", story="Xaou_BookProxy_391", sourceStory="BookShop_MiBao_1", cache="ItemCache5" },
    { text="📖 ตำราสมบัติลับ: 两界十方大藏宝录残卷", id="Esoterica_MiBao_7", cat="💎 สมบัติลับ", story="Xaou_BookProxy_392", sourceStory="BookShop_MiBao_1", cache="ItemCache6" },
    { text="📖 ตำราสมบัติลับ: 修罗血河宝录残卷", id="Esoterica_MiBao_8", cat="💎 สมบัติลับ", story="Xaou_BookProxy_393", sourceStory="BookShop_MiBao_1", cache="ItemCache7" },
    { text="📖 ตำราสมบัติลับ: 广成天书残卷", id="Esoterica_MiBao_6", cat="💎 สมบัติลับ", story="Xaou_BookProxy_394", sourceStory="BookShop_MiBao_1", cache="ItemCache8" },
    { text="📖 ตำราสมบัติลับ: 星河遗录", id="Esoterica_MiBao_9", cat="💎 สมบัติลับ", story="Xaou_BookProxy_395", sourceStory="BookShop_MiBao_1", cache="ItemCache9" },
    { text="📖 ตำราสมบัติลับ: 瑶池玉书", id="Esoterica_MiBao_10", cat="💎 สมบัติลับ", story="Xaou_BookProxy_396", sourceStory="BookShop_MiBao_1", cache="ItemCache10" },
    { text="📖 ตำราสมบัติลับ: 百毒真经残卷", id="Esoterica_MiBao_5", cat="💎 สมบัติลับ", story="Xaou_BookProxy_397", sourceStory="BookShop_MiBao_1", cache="ItemCache11" },
    { text="📖 ตำราสมบัติลับ: 真武荡魔秘宝录", id="Esoterica_MiBao_11", cat="💎 สมบัติลับ", story="Xaou_BookProxy_398", sourceStory="BookShop_MiBao_1", cache="ItemCache12" },
    { text="📖 ⛰ ตำราป้องกัน: 太虚元罡", id="Gong11_Esoterica_3", cat="🛡 การป้องกัน", story="Xaou_BookProxy_399", sourceStory="BookShop_Barrier_1", cache="ItemCache2" },
    { text="📖 ⛰ ตำราป้องกัน: 护体血罡", id="Gong5_Esoterica_7", cat="🛡 การป้องกัน", story="Xaou_BookProxy_400", sourceStory="BookShop_Barrier_1", cache="ItemCache3" },
    { text="📖 ⛰ วิชาหลอมสมบัติคุนหลี", id="Other_Esoterica_ChiLianYuan", cat="🔥 หลอมสร้าง", story="Xaou_BookProxy_401", sourceStory="BookShop_Refining_1", cache="ItemCache2" },
    { text="📖 🌳 ตำราขัดหยก", id="Gong2_Esoterica_9", cat="🔥 หลอมสร้าง", story="Xaou_BookProxy_402", sourceStory="BookShop_Refining_1", cache="ItemCache3" },
    { text="📖 🌳 ตำราหลอมสร้าง: 上清秘传造化真解", id="Gong2_Esoterica_10", cat="🔥 หลอมสร้าง", story="Xaou_BookProxy_403", sourceStory="BookShop_Refining_1", cache="ItemCache4" },
    { text="📖 🌳 ตำราหลอมสร้าง: 丙丁雷泽火", id="Gong2_Esoterica_3", cat="🔥 หลอมสร้าง", story="Xaou_BookProxy_404", sourceStory="BookShop_Refining_1", cache="ItemCache5" },
    { text="📖 🌳 บนชิงเปลวแท้ก่อนกำเนิด", id="Gong2_Esoterica_4", cat="🔥 หลอมสร้าง", story="Xaou_BookProxy_405", sourceStory="BookShop_Refining_1", cache="ItemCache6" },
    { text="📖 🌳 บันทึกสารพัดสิ่ง", id="Gong2_Esoterica_7", cat="🔥 หลอมสร้าง", story="Xaou_BookProxy_406", sourceStory="BookShop_Refining_1", cache="ItemCache7" },
    { text="📖 🌳 วิชาหลอมจิต", id="Gong2_Esoterica_2", cat="🔥 หลอมสร้าง", story="Xaou_BookProxy_407", sourceStory="BookShop_Refining_1", cache="ItemCache8" },
    { text="📖 🌳 สิบหลักหลอมศาสตรา", id="Gong2_Esoterica_8", cat="🔥 หลอมสร้าง", story="Xaou_BookProxy_408", sourceStory="BookShop_Refining_1", cache="ItemCache9" },
    { text="📖 กล่องหยกสามถ้ำ", id="SpellEsoterica_1", cat="📜 ยันต์/อาคม", story="Xaou_BookProxy_409", sourceStory="BookShop_Spell_1", cache="ItemCache2" },
    { text="📖 คัมภีร์ยันต์เทพห้าปราณ", id="SpellEsoterica_2", cat="📜 ยันต์/อาคม", story="Xaou_BookProxy_410", sourceStory="BookShop_Spell_1", cache="ItemCache3" },
    { text="📖 คู่มือยันต์ไท่ผิง", id="SpellEsoterica_5", cat="📜 ยันต์/อาคม", story="Xaou_BookProxy_411", sourceStory="BookShop_Spell_1", cache="ItemCache4" },
    { text="📖 ตำราทองยันต์เทพห้าทิศหกบัญชา", id="SpellEsoterica_3", cat="📜 ยันต์/อาคม", story="Xaou_BookProxy_412", sourceStory="BookShop_Spell_1", cache="ItemCache5" },
    { text="📖 ตำรายันต์: 与帝符文书", id="SpellEsoterica_4", cat="📜 ยันต์/อาคม", story="Xaou_BookProxy_413", sourceStory="BookShop_Spell_1", cache="ItemCache6" },
    { text="📖 สมุดภาพรับวสันต์", id="SpellEsoterica_6", cat="📜 ยันต์/อาคม", story="Xaou_BookProxy_414", sourceStory="BookShop_Spell_1", cache="ItemCache7" },
    { text="📖 ⚙ คัมภีร์หลิงจือ: 本源真法-琅琊典", id="Esoterica_LingZhi_MiFa_Ling_Jin", cat="🌿 วิชาหลิงจือ", story="Xaou_BookProxy_415", sourceStory="BookShop_LingZhi_1", cache="ItemCache2" },
    { text="📖 ⚙ คัมภีร์หลิงจือ: 逆源真法-无妄心魔咒", id="Esoterica_LingZhi_MiFa_Sha_Jin", cat="🌿 วิชาหลิงจือ", story="Xaou_BookProxy_416", sourceStory="BookShop_LingZhi_1", cache="ItemCache3" },
    { text="📖 ⛰ คัมภีร์หลิงจือ: 本源真法-蕴龙诀", id="Esoterica_LingZhi_MiFa_Ling_Tu", cat="🌿 วิชาหลิงจือ", story="Xaou_BookProxy_417", sourceStory="BookShop_LingZhi_1", cache="ItemCache4" },
    { text="📖 ⛰ คัมภีร์หลิงจือ: 逆源真法-否极无咎书", id="Esoterica_LingZhi_MiFa_Sha_Tu", cat="🌿 วิชาหลิงจือ", story="Xaou_BookProxy_418", sourceStory="BookShop_LingZhi_1", cache="ItemCache5" },
    { text="📖 🌊 คัมภีร์หลิงจือ: 本源真法-青莲书", id="Esoterica_LingZhi_MiFa_Ling_Shui", cat="🌿 วิชาหลิงจือ", story="Xaou_BookProxy_419", sourceStory="BookShop_LingZhi_1", cache="ItemCache6" },
    { text="📖 🌊 คัมภีร์หลิงจือ: 逆源真法-未济七绝体", id="Esoterica_LingZhi_MiFa_Sha_Shui", cat="🌿 วิชาหลิงจือ", story="Xaou_BookProxy_420", sourceStory="BookShop_LingZhi_1", cache="ItemCache7" },
    { text="📖 🌳 คัมภีร์หลิงจือ: 本源真法-枯荣经", id="Esoterica_LingZhi_MiFa_Ling_Mu", cat="🌿 วิชาหลิงจือ", story="Xaou_BookProxy_421", sourceStory="BookShop_LingZhi_1", cache="ItemCache8" },
    { text="📖 🌳 คัมภีร์หลิงจือ: 逆源真法-大过经", id="Esoterica_LingZhi_MiFa_Sha_Mu", cat="🌿 วิชาหลิงจือ", story="Xaou_BookProxy_422", sourceStory="BookShop_LingZhi_1", cache="ItemCache9" },
    { text="📖 🔥 คัมภีร์หลิงจือ: 本源真法-明夷录", id="Esoterica_LingZhi_MiFa_Ling_Huo", cat="🌿 วิชาหลิงจือ", story="Xaou_BookProxy_423", sourceStory="BookShop_LingZhi_1", cache="ItemCache10" },
    { text="📖 🔥 คัมภีร์หลิงจือ: 逆源真法-革天录", id="Esoterica_LingZhi_MiFa_Sha_Huo", cat="🌿 วิชาหลิงจือ", story="Xaou_BookProxy_424", sourceStory="BookShop_LingZhi_1", cache="ItemCache11" },
    { text="📖 หนังสือ: 上古秘闻：卷一", id="ShangGuYiWen_1", cat="📖 หนังสือ/บันทึก", story="Xaou_BookProxy_425", sourceStory="BookShop_Book_1", cache="ItemCache2" },
    { text="📖 หนังสือ: 上古秘闻：卷二", id="ShangGuYiWen_2", cat="📖 หนังสือ/บันทึก", story="Xaou_BookProxy_426", sourceStory="BookShop_Book_1", cache="ItemCache3" },
    { text="📖 หนังสือ: 云笈秘录：大漠篇", id="YouJi_6_4", cat="📖 หนังสือ/บันทึก", story="Xaou_BookProxy_427", sourceStory="BookShop_Book_1", cache="ItemCache4" },
    { text="📖 หนังสือ: 云笈秘录：边荒篇", id="YouJi_6_1", cat="📖 หนังสือ/บันทึก", story="Xaou_BookProxy_428", sourceStory="BookShop_Book_1", cache="ItemCache5" },
    { text="📖 หนังสือ: 云笈秘录：雪原篇", id="YouJi_6_3", cat="📖 หนังสือ/บันทึก", story="Xaou_BookProxy_429", sourceStory="BookShop_Book_1", cache="ItemCache6" },
    { text="📖 หนังสือ: 山图海志", id="YouJi_3", cat="📖 หนังสือ/บันทึก", story="Xaou_BookProxy_430", sourceStory="BookShop_Book_1", cache="ItemCache7" },
    { text="📖 หนังสือ: 御风子游记：卷一", id="YouJi_2_1", cat="📖 หนังสือ/บันทึก", story="Xaou_BookProxy_431", sourceStory="BookShop_Book_1", cache="ItemCache8" },
    { text="📖 หนังสือ: 御风子游记：卷七", id="YouJi_2_7", cat="📖 หนังสือ/บันทึก", story="Xaou_BookProxy_432", sourceStory="BookShop_Book_1", cache="ItemCache9" },
    { text="📖 หนังสือ: 御风子游记：卷三", id="YouJi_2_3", cat="📖 หนังสือ/บันทึก", story="Xaou_BookProxy_433", sourceStory="BookShop_Book_1", cache="ItemCache10" },
    { text="📖 หนังสือ: 御风子游记：卷二", id="YouJi_2_2", cat="📖 หนังสือ/บันทึก", story="Xaou_BookProxy_434", sourceStory="BookShop_Book_1", cache="ItemCache11" },
    { text="📖 หนังสือ: 御风子游记：卷五", id="YouJi_2_5", cat="📖 หนังสือ/บันทึก", story="Xaou_BookProxy_435", sourceStory="BookShop_Book_1", cache="ItemCache12" },
    { text="📖 หนังสือ: 御风子游记：卷六", id="YouJi_2_6", cat="📖 หนังสือ/บันทึก", story="Xaou_BookProxy_436", sourceStory="BookShop_Book_1", cache="ItemCache13" },
    { text="📖 หนังสือ: 御风子游记：卷四", id="YouJi_2_4", cat="📖 หนังสือ/บันทึก", story="Xaou_BookProxy_437", sourceStory="BookShop_Book_1", cache="ItemCache14" },
    { text="📖 หนังสือ: 拾遗录：上册", id="YouJi_4_1", cat="📖 หนังสือ/บันทึก", story="Xaou_BookProxy_438", sourceStory="BookShop_Book_1", cache="ItemCache15" },
    { text="📖 หนังสือ: 拾遗录：下册", id="YouJi_4_3", cat="📖 หนังสือ/บันทึก", story="Xaou_BookProxy_439", sourceStory="BookShop_Book_1", cache="ItemCache16" },
    { text="📖 หนังสือ: 拾遗录：中册", id="YouJi_4_2", cat="📖 หนังสือ/บันทึก", story="Xaou_BookProxy_440", sourceStory="BookShop_Book_1", cache="ItemCache17" },
    { text="📖 หนังสือ: 游仙录", id="YouJi_5", cat="📖 หนังสือ/บันทึก", story="Xaou_BookProxy_441", sourceStory="BookShop_Book_1", cache="ItemCache18" },
    { text="📖 หนังสือ: 神州志：中原篇", id="YouJi_1_2", cat="📖 หนังสือ/บันทึก", story="Xaou_BookProxy_442", sourceStory="BookShop_Book_1", cache="ItemCache19" },
    { text="📖 หนังสือ: 神州志：江岸篇", id="YouJi_1_3", cat="📖 หนังสือ/บันทึก", story="Xaou_BookProxy_443", sourceStory="BookShop_Book_1", cache="ItemCache20" },
    { text="📖 หนังสือ: 群仙录：卷一", id="NanGongYiCe", cat="📖 หนังสือ/บันทึก", story="Xaou_BookProxy_444", sourceStory="BookShop_Book_1", cache="ItemCache21" },
    { text="📖 หนังสือ: 群仙录：卷三", id="QunXianLu_3", cat="📖 หนังสือ/บันทึก", story="Xaou_BookProxy_445", sourceStory="BookShop_Book_2", cache="ItemCache2" },
    { text="📖 หนังสือ: 群仙录：卷二", id="QunXianLu_2", cat="📖 หนังสือ/บันทึก", story="Xaou_BookProxy_446", sourceStory="BookShop_Book_2", cache="ItemCache3" },
    { text="📖 คัมภีร์พิเศษ: 三尸分神法：善我之斩", id="Other_Esoterica_FenShen2", cat="📚 คัมภีร์อื่น ๆ", story="Xaou_BookProxy_447", sourceStory="BookShop_Other_1", cache="ItemCache2" },
    { text="📖 คัมภีร์พิเศษ: 三尸分神法：恶我之斩", id="Other_Esoterica_FenShen3", cat="📚 คัมภีร์อื่น ๆ", story="Xaou_BookProxy_448", sourceStory="BookShop_Other_1", cache="ItemCache3" },
    { text="📖 คัมภีร์พิเศษ: 三尸分神法：本我之斩", id="Other_Esoterica_FenShen4", cat="📚 คัมภีร์อื่น ๆ", story="Xaou_BookProxy_449", sourceStory="BookShop_Other_1", cache="ItemCache4" },
    { text="📖 คัมภีร์พิเศษ: 五炁破霞", id="Other_Esoterica_QuQiJue", cat="📚 คัมภีร์อื่น ๆ", story="Xaou_BookProxy_450", sourceStory="BookShop_Other_1", cache="ItemCache5" },
    { text="📖 คัมภีร์พิเศษ: 炎黄通史", id="Other_Esoterica_YanHuangTongShi", cat="📚 คัมภีร์อื่น ๆ", story="Xaou_BookProxy_451", sourceStory="BookShop_Other_1", cache="ItemCache6" },
    { text="📖 พลังปะทุ", id="Esoterica_LunHui3", cat="📚 คัมภีร์อื่น ๆ", story="Xaou_BookProxy_452", sourceStory="BookShop_Other_1", cache="ItemCache7" },
    { text="📖 ยันต์เซินเซิน", id="Esoterica_LunHui5", cat="📚 คัมภีร์อื่น ๆ", story="Xaou_BookProxy_453", sourceStory="BookShop_Other_1", cache="ItemCache8" },
    { text="📖 วสันต์คืนผืนดิน", id="Esoterica_LunHui2", cat="📚 คัมภีร์อื่น ๆ", story="Xaou_BookProxy_454", sourceStory="BookShop_Other_1", cache="ItemCache9" },
    { text="📖 วิชาเซียนคุนหลุน", id="Esoterica_LunHui4", cat="📚 คัมภีร์อื่น ๆ", story="Xaou_BookProxy_455", sourceStory="BookShop_Other_1", cache="ItemCache10" },
    { text="📖 วิชาแท้วิญญาณหยินหยาง", id="Other_Esoterica_ZhuLongDan", cat="📚 คัมภีร์อื่น ๆ", story="Xaou_BookProxy_456", sourceStory="BookShop_Other_1", cache="ItemCache11" },
    { text="📖 หนึ่งปราณแปรสามพิสุทธิ์", id="Other_Esoterica_FenShen1", cat="📚 คัมภีร์อื่น ๆ", story="Xaou_BookProxy_457", sourceStory="BookShop_Other_1", cache="ItemCache12" },
    { text="📖 หมัดลูกบอลป่า", id="Esoterica_LunHui1", cat="📚 คัมภีร์อื่น ๆ", story="Xaou_BookProxy_458", sourceStory="BookShop_Other_1", cache="ItemCache13" },
    { text="📖 ⛰ เคล็ดขุนเขาแม่น้ำ", id="Other_Esoterica_ShanHeJue", cat="📚 คัมภีร์อื่น ๆ", story="Xaou_BookProxy_459", sourceStory="BookShop_Other_1", cache="ItemCache14" },
    { text="📖 🌊 วิชาแท้วิญญาณมังกร", id="Other_Esoterica_LongDan", cat="📚 คัมภีร์อื่น ๆ", story="Xaou_BookProxy_460", sourceStory="BookShop_Other_1", cache="ItemCache15" },
    { text="📖 🔥 วิชาแท้วิญญาณหงส์", id="Other_Esoterica_FengDan", cat="📚 คัมภีร์อื่น ๆ", story="Xaou_BookProxy_461", sourceStory="BookShop_Other_1", cache="ItemCache16" },
    { text="📖 กระบี่ยันต์บันทึก", id="Gong12_Esoterica_3", cat="📦 อื่น ๆ", story="Xaou_BookProxy_462", sourceStory="BookShop_Other2_1", cache="ItemCache2" },
    { text="📖 คัมภีร์: 东木分神书", id="Gong12_Esoterica_12", cat="📦 อื่น ๆ", story="Xaou_BookProxy_463", sourceStory="BookShop_Other2_1", cache="ItemCache3" },
    { text="📖 คัมภีร์: 云气汇流", id="Gong12_Esoterica_9", cat="📦 อื่น ๆ", story="Xaou_BookProxy_464", sourceStory="BookShop_Other2_1", cache="ItemCache4" },
    { text="📖 คัมภีร์: 五气归源", id="Gong4_Esoterica_4", cat="📦 อื่น ๆ", story="Xaou_BookProxy_465", sourceStory="BookShop_Other2_1", cache="ItemCache5" },
    { text="📖 คัมภีร์: 借天符", id="Gong12_Esoterica_6", cat="📦 อื่น ๆ", story="Xaou_BookProxy_466", sourceStory="BookShop_Other2_1", cache="ItemCache6" },
    { text="📖 คัมภีร์: 天真论", id="Gong12_Esoterica_11", cat="📦 อื่น ๆ", story="Xaou_BookProxy_467", sourceStory="BookShop_Other2_1", cache="ItemCache7" },
    { text="📖 คัมภีร์: 玉京飞流法", id="Gong4_Esoterica_1", cat="📦 อื่น ๆ", story="Xaou_BookProxy_468", sourceStory="BookShop_Other2_1", cache="ItemCache8" },
    { text="📖 คัมภีร์: 结云经", id="Gong12_Esoterica_10", cat="📦 อื่น ๆ", story="Xaou_BookProxy_469", sourceStory="BookShop_Other2_1", cache="ItemCache9" },
    { text="📖 คัมภีร์: 谷神大法", id="Gong4_Esoterica_6", cat="📦 อื่น ๆ", story="Xaou_BookProxy_470", sourceStory="BookShop_Other2_1", cache="ItemCache10" },
    { text="📖 คัมภีร์: 通天符法", id="Gong12_Esoterica_5", cat="📦 อื่น ๆ", story="Xaou_BookProxy_471", sourceStory="BookShop_Other2_1", cache="ItemCache11" },
    { text="📖 คัมภีร์: 通符书", id="Gong12_Esoterica_1", cat="📦 อื่น ๆ", story="Xaou_BookProxy_472", sourceStory="BookShop_Other2_1", cache="ItemCache12" },
    { text="📖 มนต์ยันต์บันทึก", id="Gong12_Esoterica_4", cat="📦 อื่น ๆ", story="Xaou_BookProxy_473", sourceStory="BookShop_Other2_1", cache="ItemCache13" },
    { text="📖 ม็อดสูญหาย", id="Esoterica_SYS_LOST", cat="📦 อื่น ๆ", story="Xaou_BookProxy_474", sourceStory="BookShop_Other2_1", cache="ItemCache14" },
    { text="📖 ลี้ลับยันต์บันทึก", id="Gong12_Esoterica_2", cat="📦 อื่น ๆ", story="Xaou_BookProxy_475", sourceStory="BookShop_Other2_1", cache="ItemCache15" },
    { text="📖 เมฆธาตุวิชา", id="Gong12_Esoterica_8", cat="📦 อื่น ๆ", story="Xaou_BookProxy_476", sourceStory="BookShop_Other2_1", cache="ItemCache16" },
    { text="📖 ไร้บนเทพยันต์", id="Gong12_Esoterica_7", cat="📦 อื่น ๆ", story="Xaou_BookProxy_477", sourceStory="BookShop_Other2_1", cache="ItemCache17" },
    { text="📖 ⚙ คัมภีร์: 七杀魔体", id="Gong3_Esoterica_2", cat="📦 อื่น ๆ", story="Xaou_BookProxy_478", sourceStory="BookShop_Other2_1", cache="ItemCache18" },
    { text="📖 ⚙ คัมภีร์: 司南经", id="Gong8_Esoterica_2", cat="📦 อื่น ๆ", story="Xaou_BookProxy_479", sourceStory="BookShop_Other2_1", cache="ItemCache19" },
    { text="📖 ⚙ คัมภีร์: 庚金元神", id="Gong4_Esoterica_8", cat="📦 อื่น ๆ", story="Xaou_BookProxy_480", sourceStory="BookShop_Other2_1", cache="ItemCache20" },
    { text="📖 ⛰ คัมภีร์: 九州大法", id="Gong11_Esoterica_5", cat="📦 อื่น ๆ", story="Xaou_BookProxy_481", sourceStory="BookShop_Other2_1", cache="ItemCache21" },
    { text="📖 ⛰ คัมภีร์: 太阴锻体", id="Gong11_Esoterica_1", cat="📦 อื่น ๆ", story="Xaou_BookProxy_482", sourceStory="BookShop_Other2_2", cache="ItemCache2" },
    { text="📖 ⛰ คัมภีร์: 戊土元神", id="Gong4_Esoterica_12", cat="📦 อื่น ๆ", story="Xaou_BookProxy_483", sourceStory="BookShop_Other2_2", cache="ItemCache3" },
    { text="📖 ⛰ คัมภีร์: 虚空谒神法", id="Gong11_Esoterica_4", cat="📦 อื่น ๆ", story="Xaou_BookProxy_484", sourceStory="BookShop_Other2_2", cache="ItemCache4" },
    { text="📖 ⛰ คัมภีร์: 血骨炼形", id="Gong5_Esoterica_6", cat="📦 อื่น ๆ", story="Xaou_BookProxy_485", sourceStory="BookShop_Other2_2", cache="ItemCache5" },
    { text="📖 ⛰ คุนต้นกำเนิดแท้ปราณ", id="Gong11_Esoterica_16", cat="📦 อื่น ๆ", story="Xaou_BookProxy_486", sourceStory="BookShop_Other2_2", cache="ItemCache6" },
    { text="📖 🌊 คัมภีร์: 壬水元神", id="Gong4_Esoterica_10", cat="📦 อื่น ๆ", story="Xaou_BookProxy_487", sourceStory="BookShop_Other2_2", cache="ItemCache7" },
    { text="📖 🌊 รวมกระแสกังซา", id="Gong1_Esoterica_4", cat="📦 อื่น ๆ", story="Xaou_BookProxy_488", sourceStory="BookShop_Other2_2", cache="ItemCache8" },
    { text="📖 🌊 เคล็ดเก็บวารี", id="Gong1_Esoterica_6", cat="📦 อื่น ๆ", story="Xaou_BookProxy_489", sourceStory="BookShop_Other2_2", cache="ItemCache9" },
    { text="📖 🌳 คัมภีร์: 甲木元神", id="Gong4_Esoterica_9", cat="📦 อื่น ๆ", story="Xaou_BookProxy_490", sourceStory="BookShop_Other2_2", cache="ItemCache10" },
    { text="📖 🌳 คัมภีร์: 真吾之体·一阶", id="Gong9_Esoterica_13", cat="📦 อื่น ๆ", story="Xaou_BookProxy_491", sourceStory="BookShop_Other2_2", cache="ItemCache11" },
    { text="📖 🌳 คัมภีร์: 轮回经", id="Gong9_Esoterica_6", cat="📦 อื่น ๆ", story="Xaou_BookProxy_492", sourceStory="BookShop_Other2_2", cache="ItemCache12" },
    { text="📖 🌳 คัมภีร์: 通息诀", id="Gong9_Esoterica_9", cat="📦 อื่น ๆ", story="Xaou_BookProxy_493", sourceStory="BookShop_Other2_2", cache="ItemCache13" },
    { text="📖 🌳 เคล็ดร้อยหลอม", id="Gong2_Esoterica_1", cat="📦 อื่น ๆ", story="Xaou_BookProxy_494", sourceStory="BookShop_Other2_2", cache="ItemCache14" },
    { text="📖 🌳 เปลวใจ", id="Gong2_Esoterica_5", cat="📦 อื่น ๆ", story="Xaou_BookProxy_495", sourceStory="BookShop_Other2_2", cache="ItemCache15" },
    { text="📖 🔥 คัมภีร์: 三阳真脉", id="Gong10_Esoterica_7", cat="📦 อื่น ๆ", story="Xaou_BookProxy_496", sourceStory="BookShop_Other2_2", cache="ItemCache16" },
    { text="📖 🔥 คัมภีร์: 丙火元神", id="Gong4_Esoterica_11", cat="📦 อื่น ๆ", story="Xaou_BookProxy_497", sourceStory="BookShop_Other2_2", cache="ItemCache17" },
    { text="📖 🔥 คัมภีร์: 养吾经", id="Gong7_Esoterica_6", cat="📦 อื่น ๆ", story="Xaou_BookProxy_498", sourceStory="BookShop_Other2_2", cache="ItemCache18" },
    { text="📖 🔥 คัมภีร์: 玉液炼形诀", id="Gong6_Esoterica_1", cat="📦 อื่น ๆ", story="Xaou_BookProxy_499", sourceStory="BookShop_Other2_2", cache="ItemCache19" },
    { text="📖 🔥 คัมภีร์: 金乌观", id="Gong10_Esoterica_5", cat="📦 อื่น ๆ", story="Xaou_BookProxy_500", sourceStory="BookShop_Other2_2", cache="ItemCache20" },
    { text="📖 🔥 คืนต้นกำเนิดเคล็ด", id="Gong6_Esoterica_13", cat="📦 อื่น ๆ", story="Xaou_BookProxy_501", sourceStory="BookShop_Other2_2", cache="ItemCache21" },
    { text="📖 🔥 ร่วมใจเคล็ด", id="Gong7_Esoterica_3", cat="📦 อื่น ๆ", story="Xaou_BookProxy_502", sourceStory="BookShop_Other2_3", cache="ItemCache2" },
    { text="📖 🔥 วายุเทพเมฆกาย", id="Gong7_Esoterica_9", cat="📦 อื่น ๆ", story="Xaou_BookProxy_503", sourceStory="BookShop_Other2_3", cache="ItemCache3" },
}

function Xaou_BookShow(msg, title)
    if Xaou_Show ~= nil then
        Xaou_Show(tostring(msg or ""), title or "คัมภีร์")
    elseif world ~= nil and world.ShowMsgBox ~= nil then
        world:ShowMsgBox(tostring(msg or ""), title or "คัมภีร์")
    else
        print("[XaouBook] " .. tostring(msg or ""))
    end
end

function Xaou_BookCleanText(text)
    text = tostring(text or "")
    text = string.gsub(text, "^%d+%.%s*", "")
    return text
end

function Xaou_MatchBookCommand(book, keyword)
    keyword = tostring(keyword or "")
    if keyword == "" or keyword == "ค้นหา ID/ชื่อ" then return true end
    keyword = string.lower(keyword)
    if book == nil then return false end
    if string.find(string.lower(tostring(book.text or "")), keyword, 1, true) then return true end
    if string.find(string.lower(tostring(book.id or "")), keyword, 1, true) then return true end
    if string.find(string.lower(tostring(book.cat or "")), keyword, 1, true) then return true end
    if string.find(string.lower(tostring(book.sourceStory or "")), keyword, 1, true) then return true end
    return false
end

function Xaou_GetBookList(category, keyword)
    local result = {}
    category = tostring(category or "ทั้งหมด")
    for _, book in ipairs(Xaou_BookList or {}) do
        local okCat = (category == "" or category == "ทั้งหมด" or tostring(book.cat or "") == category)
        if okCat and Xaou_MatchBookCommand(book, keyword) then
            table.insert(result, book)
        end
    end
    return result
end
