-- Xaou ItemPack อาวุธ
Xaou_ItemPacks = Xaou_ItemPacks or {}
table.insert(Xaou_ItemPacks, {
    name = "Special Pack",
    items = {
        { id = "Item_Cape_Nomal1", count = 1, cat = "อาวุธ" },
        { id = "Item_Cape_Nomal2", count = 100, cat = "อาวุธ" },
        { id = "Item_Cape_Nomal3", count = 1, cat = "อาวุธ" },
        { id = "Item_Cape_Nomal4", count = 1, cat = "อาวุธ" },
        { id = "Item_Cape_Sp1", count = 1, cat = "อาวุธ" },
        { id = "Item_Cape_Sp2", count = 1, cat = "อาวุธ" },
        { id = "Item_Cape_Sp3", count = 1, cat = "อาวุธ" },
        { id = "Item_Cape_Sp4", count = 1, cat = "อาวุธ" },
        { id = "Item_Cape_Sp5", count = 1, cat = "อาวุธ" },
        { id = "Item_Cape_Sp6", count = 1, cat = "อาวุธ" },
        { id = "Item_Cape_Sp7", count = 1, cat = "อาวุธ" },
        { id = "Item_Cape_Sp9", count = 1, cat = "อาวุธ" },
        { id = "Item_Cape_Sp10", count = 1, cat = "อาวุธ" },
        { id = "Item_WeaponFuChen", count = 1, cat = "อาวุธ" },
        { id = "Item_WeaponDaoSword", count = 1, cat = "อาวุธ" },
        { id = "Item_SummerClothes", count = 1, cat = "อาวุธ" },
        { id = "Item_SilkClothes", count = 1, cat = "อาวุธ" },
        { id = "Item_PracticeClothes", count = 1, cat = "อาวุธ" },
        { id = "Item_FormalClothes", count = 1, cat = "อาวุธ" },
        { id = "Item_WinterClothes", count = 1, cat = "อาวุธ" },
        { id = "Item_SP_Clothes1", count = 1, cat = "อาวุธ" },
        { id = "Item_SP_Clothes2", count = 1, cat = "อาวุธ" },
        { id = "Item_SP_Clothes3", count = 1, cat = "อาวุธ" },
        { id = "Item_SP_Clothes4", count = 1, cat = "อาวุธ" },
        { id = "Item_SP_Clothes5", count = 1, cat = "อาวุธ" },
        { id = "Item_SP_Clothes6", count = 1, cat = "อาวุธ" },
        { id = "Item_SP_Clothes7", count = 1, cat = "อาวุธ" },
        { id = "Item_SP_Clothes8", count = 1, cat = "อาวุธ" },
        { id = "Item_SP_Clothes9", count = 1, cat = "อาวุธ" },
        { id = "Item_SP_Clothes10", count = 1, cat = "อาวุธ" },
        { id = "FaBaoBase", count = 1, cat = "อาวุธ" },
        { id = "FaBaoTest", count = 1, cat = "อาวุธ" },
        { id = "FightFaBao", count = 1, cat = "อาวุธ" },
        { id = "TreasureFabao", count = 1, cat = "อาวุธ" },
        { id = "Item_SummerTrousers", count = 1, cat = "อาวุธ" },
        { id = "Item_SilkTrousers", count = 1, cat = "อาวุธ" },
        { id = "Item_PracticeTrousers", count = 1, cat = "อาวุธ" },
        { id = "Item_FormalTrousers", count = 1, cat = "อาวุธ" },
        { id = "Item_WinterTrousers", count = 1, cat = "อาวุธ" },
        { id = "Item_SP_Trousers1", count = 1, cat = "อาวุธ" },
        { id = "Item_SP_Trousers2", count = 1, cat = "อาวุธ" },
        { id = "Item_SP_Trousers3", count = 1, cat = "อาวุธ" },
        { id = "Item_SP_Trousers4", count = 1, cat = "อาวุธ" },
        { id = "Item_SP_Trousers5", count = 1, cat = "อาวุธ" },
        { id = "Item_SP_Trousers6", count = 1, cat = "อาวุธ" },
        { id = "Item_SP_Trousers7", count = 1, cat = "อาวุธ" },
        { id = "Item_SP_Trousers8", count = 1, cat = "อาวุธ" },
        { id = "Item_SP_Trousers9", count = 1, cat = "อาวุธ" },
        { id = "Item_SP_Trousers10", count = 1, cat = "อาวุธ" },
        { id = "Item_WeaponBow", count = 1, cat = "อาวุธ" },
        { id = "Item_WeaponWoodBow", count = 1, cat = "อาวุธ" },
        { id = "Item_WeaponKnife", count = 1, cat = "อาวุธ" },
        { id = "Item_WeaponLance", count = 1, cat = "อาวุธ" },
        { id = "Item_WeaponSword", count = 1, cat = "อาวุธ" },
        { id = "Item_WeaponHalbert", count = 1, cat = "อาวุธ" },
        { id = "Item_WeaponAxeRing", count = 1, cat = "อาวุธ" },
        { id = "SP_Sword1", count = 1, cat = "อาวุธ" },
        { id = "SP_Sword2", count = 1, cat = "อาวุธ" },
        { id = "SP_Sword3", count = 1, cat = "อาวุธ" },
        { id = "SP_Sword4", count = 1, cat = "อาวุธ" },
        { id = "SP_Bow1", count = 1, cat = "อาวุธ" },
    

        
    }
})
